export interface Notice {
  sheet: string
  name: string
  url: string
  pages?: number
  bytes?: number
}

export const NOTICES: Record<string, Notice[]> = {
  'auvergne-rhone-alpes': [
    { sheet: '0597', name: 'BOURBON L\'ARCHAMBAULT', url: 'http://ficheinfoterre.brgm.fr/Notices/0597N.pdf' },
    { sheet: '0598', name: 'MOULINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0598N.pdf' },
    { sheet: '0599', name: 'DOMPIERRE-SUR-BESBRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0599N.pdf' },
    { sheet: '0620', name: 'MONTMARAULT', url: 'http://ficheinfoterre.brgm.fr/Notices/0620N.pdf' },
    { sheet: '0621', name: 'ST-POURCAIN-SUR-SIOULE', url: 'http://ficheinfoterre.brgm.fr/Notices/0621N.pdf' },
    { sheet: '0622', name: 'LE DONJON', url: 'http://ficheinfoterre.brgm.fr/Notices/0622N.pdf' },
    { sheet: '0623', name: 'CHAROLLES', url: 'http://ficheinfoterre.brgm.fr/Notices/0623N.pdf' },
    { sheet: '0624', name: 'CLUNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0624N.pdf' },
    { sheet: '0643', name: 'EVAUX-LES-BAINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0643N.pdf' },
    { sheet: '0644', name: 'MONTAIGUT-EN-COMBRAILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0644N.pdf' },
    { sheet: '0645', name: 'GANNAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0645N.pdf' },
    { sheet: '0646', name: 'VICHY', url: 'http://ficheinfoterre.brgm.fr/Notices/0646N.pdf' },
    { sheet: '0647', name: 'LAPALISSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0647N.pdf' },
    { sheet: '0648', name: 'CHARLIEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0648N.pdf' },
    { sheet: '0649', name: 'BEAUJEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0649N.pdf' },
    { sheet: '0650', name: 'BELLEVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0650N.pdf' },
    { sheet: '0651', name: 'BOURG-EN-BRESSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0651N.pdf' },
    { sheet: '0667', name: 'AUBUSSON', url: 'http://ficheinfoterre.brgm.fr/Notices/0667N.pdf' },
    { sheet: '0668', name: 'ST-GERVAIS-D\'AUVERGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0668N.pdf' },
    { sheet: '0669', name: 'AIGUEPERSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0669N.pdf' },
    { sheet: '0670', name: 'MARINGUES', url: 'http://ficheinfoterre.brgm.fr/Notices/0670N.pdf' },
    { sheet: '0671', name: 'LE MAYET-DE-MONTAGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0671N.pdf' },
    { sheet: '0672', name: 'ROANNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0672N.pdf' },
    { sheet: '0673', name: 'AMPLEPUIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0673N.pdf' },
    { sheet: '0674', name: 'VILLEFRANCHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0674N.pdf' },
    { sheet: '0675', name: 'AMBERIEU-EN-BUGEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0675N.pdf' },
    { sheet: '0676', name: 'ST-RAMBERT-EN-BUGEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0676N.pdf' },
    { sheet: '0677', name: 'SEYSSEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0677N.pdf' },
    { sheet: '0678', name: 'ANNECY-BONNEVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0678N.pdf' },
    { sheet: '0679', name: 'CLUSES', url: 'http://ficheinfoterre.brgm.fr/Notices/0679N.pdf' },
    { sheet: '0680', name: 'CHAMONIX', url: 'http://ficheinfoterre.brgm.fr/Notices/0680N.pdf' },
    { sheet: '0692', name: 'PONTGIBAUD', url: 'http://ficheinfoterre.brgm.fr/Notices/0692N.pdf' },
    { sheet: '0693', name: 'CLERMONT-FERRAND', url: 'http://ficheinfoterre.brgm.fr/Notices/0693N.pdf' },
    { sheet: '0694', name: 'THIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0694N.pdf' },
    { sheet: '0695', name: 'NOIRETABLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0695N.pdf' },
    { sheet: '0696', name: 'FEURS', url: 'http://ficheinfoterre.brgm.fr/Notices/0696N.pdf' },
    { sheet: '0697', name: 'TARARE', url: 'http://ficheinfoterre.brgm.fr/Notices/0697N.pdf' },
    { sheet: '0698', name: 'LYON', url: 'http://ficheinfoterre.brgm.fr/Notices/0698N.pdf' },
    { sheet: '0699', name: 'MONTLUEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0699N.pdf' },
    { sheet: '0700', name: 'BELLEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0700N.pdf' },
    { sheet: '0701', name: 'RUMILLY', url: 'http://ficheinfoterre.brgm.fr/Notices/0701N.pdf' },
    { sheet: '0702', name: 'ANNECY-UGINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0702N.pdf' },
    { sheet: '0703', name: 'ST-GERVAIS-LES-BAINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0703N.pdf' },
    { sheet: '0704', name: 'MONT-BLANC', url: 'http://ficheinfoterre.brgm.fr/Notices/0704N.pdf' },
    { sheet: '0716', name: 'BOURG-LASTIC', url: 'http://ficheinfoterre.brgm.fr/Notices/0716N.pdf' },
    { sheet: '0717', name: 'VEYRE-MONTON', url: 'http://ficheinfoterre.brgm.fr/Notices/0717N.pdf' },
    { sheet: '0718', name: 'ISSOIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0718N.pdf' },
    { sheet: '0719', name: 'AMBERT', url: 'http://ficheinfoterre.brgm.fr/Notices/0719N.pdf' },
    { sheet: '0720', name: 'MONTBRISON', url: 'http://ficheinfoterre.brgm.fr/Notices/0720N.pdf' },
    { sheet: '0721', name: 'ST-SYMPHORIEN-SUR-COISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0721N.pdf' },
    { sheet: '0722', name: 'GIVORS', url: 'http://ficheinfoterre.brgm.fr/Notices/0722N.pdf' },
    { sheet: '0723', name: 'BOURGOIN-JALLIEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0723N.pdf' },
    { sheet: '0724', name: 'LA TOUR-DU-PIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0724N.pdf' },
    { sheet: '0725', name: 'CHAMBERY', url: 'http://ficheinfoterre.brgm.fr/Notices/0725N.pdf' },
    { sheet: '0726', name: 'ALBERTVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0726N.pdf' },
    { sheet: '0727', name: 'BOURG-ST-MAURICE', url: 'http://ficheinfoterre.brgm.fr/Notices/0727N.pdf' },
    { sheet: '0728', name: 'SAINTE-FOY-TARENTAISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0728N.pdf' },
    { sheet: '0740', name: 'LA TOUR D\'AUVERGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0740N.pdf' },
    { sheet: '0741', name: 'BESSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0741N.pdf' },
    { sheet: '0742', name: 'ST-GERMAIN-LEMBRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0742N.pdf' },
    { sheet: '0743', name: 'ARLANC', url: 'http://ficheinfoterre.brgm.fr/Notices/0743N.pdf' },
    { sheet: '0744', name: 'FIRMINY', url: 'http://ficheinfoterre.brgm.fr/Notices/0744N.pdf' },
    { sheet: '0745', name: 'ST-ETIENNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0745N.pdf' },
    { sheet: '0746', name: 'VIENNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0746N.pdf' },
    { sheet: '0747', name: 'LA COTE-ST-ANDRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0747N.pdf' },
    { sheet: '0748', name: 'VOIRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0748N.pdf' },
    { sheet: '0749', name: 'MONTMELIAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0749N.pdf' },
    { sheet: '0750', name: 'LA ROCHETTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0750N.pdf' },
    { sheet: '0751', name: 'MOUTIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0751N.pdf' },
    { sheet: '0752', name: 'TIGNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0752N.pdf' },
    { sheet: '0764', name: 'RIOM-ES-MONTAGNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0764N.pdf' },
    { sheet: '0765', name: 'MASSIAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0765N.pdf' },
    { sheet: '0766', name: 'BRIOUDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0766N.pdf' },
    { sheet: '0767', name: 'CRAPONNE-SUR-ARZON', url: 'http://ficheinfoterre.brgm.fr/Notices/0767N.pdf' },
    { sheet: '0768', name: 'MONISTROL-SUR-LOIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0768N.pdf' },
    { sheet: '0769', name: 'ANNONAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0769N.pdf' },
    { sheet: '0770', name: 'SERRIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0770N.pdf' },
    { sheet: '0771', name: 'BEAUREPAIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0771N.pdf' },
    { sheet: '0772', name: 'GRENOBLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0772N.pdf' },
    { sheet: '0773', name: 'DOMENE', url: 'http://ficheinfoterre.brgm.fr/Notices/0773N.pdf' },
    { sheet: '0774', name: 'ST-JEAN-DE-MAURIENNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0774N.pdf' },
    { sheet: '0775', name: 'MODANE', url: 'http://ficheinfoterre.brgm.fr/Notices/0775N.pdf' },
    { sheet: '0776', name: 'LANSLEBOURG-MONT D\'AMBIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0776N.pdf' },
    { sheet: '0789', name: 'ST-FLOUR', url: 'http://ficheinfoterre.brgm.fr/Notices/0789N.pdf' },
    { sheet: '0790', name: 'LANGEAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0790N.pdf' },
    { sheet: '0791', name: 'LE PUY', url: 'http://ficheinfoterre.brgm.fr/Notices/0791N.pdf' },
    { sheet: '0792', name: 'YSSINGEAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0792N.pdf' },
    { sheet: '0793', name: 'ST-AGREVE', url: 'http://ficheinfoterre.brgm.fr/Notices/0793N.pdf' },
    { sheet: '0794', name: 'TOURNON', url: 'http://ficheinfoterre.brgm.fr/Notices/0794N.pdf' },
    { sheet: '0795', name: 'ROMANS-SUR-ISERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0795N.pdf' },
    { sheet: '0796', name: 'VIF', url: 'http://ficheinfoterre.brgm.fr/Notices/0796N.pdf' },
    { sheet: '0797', name: 'VIZILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0797N.pdf' },
    { sheet: '0799', name: 'NEVACHE- BARDONECCHIA-MODANE', url: 'http://ficheinfoterre.brgm.fr/Notices/0799N.pdf' },
    { sheet: '0814', name: 'SAUGUES', url: 'http://ficheinfoterre.brgm.fr/Notices/0814N.pdf' },
    { sheet: '0815', name: 'CAYRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0815N.pdf' },
    { sheet: '0816', name: 'LE MONASTIER-SUR-GAZEILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0816N.pdf' },
    { sheet: '0817', name: 'LAMASTRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0817N.pdf' },
    { sheet: '0818', name: 'VALENCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0818N.pdf' },
    { sheet: '0819', name: 'CHARPEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0819N.pdf' },
    { sheet: '0820', name: 'LA CHAPELLE-EN-VERCORS', url: 'http://ficheinfoterre.brgm.fr/Notices/0820N.pdf' },
    { sheet: '0821', name: 'LA MURE', url: 'http://ficheinfoterre.brgm.fr/Notices/0821N.pdf' },
    { sheet: '0822', name: 'ST-CHRISTOPHE-EN-OISANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0822N.pdf' },
    { sheet: '0838', name: 'ST-CHELY D\'APCHER', url: 'http://ficheinfoterre.brgm.fr/Notices/0838N.pdf' },
    { sheet: '0839', name: 'LANGOGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0839N.pdf' },
    { sheet: '0840', name: 'BURZET', url: 'http://ficheinfoterre.brgm.fr/Notices/0840N.pdf' },
    { sheet: '0841', name: 'PRIVAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0841N.pdf' },
    { sheet: '0842', name: 'CREST', url: 'http://ficheinfoterre.brgm.fr/Notices/0842N.pdf' },
    { sheet: '0843', name: 'DIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0843N.pdf' },
    { sheet: '0844', name: 'MENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0844N.pdf' },
    { sheet: '0862', name: 'MENDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0862N.pdf' },
    { sheet: '0863', name: 'LE BLEYMARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0863N.pdf' },
    { sheet: '0864', name: 'LARGENTIERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0864N.pdf' },
    { sheet: '0865', name: 'AUBENAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0865N.pdf' },
    { sheet: '0866', name: 'MONTELIMAR', url: 'http://ficheinfoterre.brgm.fr/Notices/0866N.pdf' },
    { sheet: '0867', name: 'DIEULEFIT', url: 'http://ficheinfoterre.brgm.fr/Notices/0867N.pdf' },
    { sheet: '0868', name: 'LUC-EN-DIOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0868N.pdf' },
    { sheet: '0889', name: 'BOURG-ST-ANDEOL', url: 'http://ficheinfoterre.brgm.fr/Notices/0889N.pdf' },
    { sheet: '0891', name: 'NYONS', url: 'http://ficheinfoterre.brgm.fr/Notices/0891N.pdf' },
  ],
  'bourgogne-franche-comte': [
    { sheet: '0367', name: 'JOIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0367N.pdf' },
    { sheet: '0368', name: 'ST-FLORENTIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0368N.pdf' },
    { sheet: '0369', name: 'CHAOURCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0369N.pdf' },
    { sheet: '0370', name: 'LES RICEYS', url: 'http://ficheinfoterre.brgm.fr/Notices/0370N.pdf' },
    { sheet: '0402', name: 'AUXERRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0402N.pdf' },
    { sheet: '0403', name: 'CHABLIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0403N.pdf' },
    { sheet: '0404', name: 'TONNERRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0404N.pdf' },
    { sheet: '0405', name: 'CHATILLON-SUR-SEINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0405N.pdf' },
    { sheet: '0406', name: 'RECEY-SUR-OURCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0406N.pdf' },
    { sheet: '0434', name: 'COURSON-LES-CARRIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0434N.pdf' },
    { sheet: '0435', name: 'VERMENTON', url: 'http://ficheinfoterre.brgm.fr/Notices/0435N.pdf' },
    { sheet: '0436', name: 'NOYERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0436N.pdf' },
    { sheet: '0437', name: 'MONTBARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0437N.pdf' },
    { sheet: '0438', name: 'AIGNAY-LE-DUC', url: 'http://ficheinfoterre.brgm.fr/Notices/0438N.pdf' },
    { sheet: '0439', name: 'IS-SUR-TILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0439N.pdf' },
    { sheet: '0440', name: 'CHAMPLITTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0440N.pdf' },
    { sheet: '0441', name: 'PORT-SUR-SAONE', url: 'http://ficheinfoterre.brgm.fr/Notices/0441N.pdf' },
    { sheet: '0465', name: 'CLAMECY', url: 'http://ficheinfoterre.brgm.fr/Notices/0465N.pdf' },
    { sheet: '0466', name: 'AVALLON', url: 'http://ficheinfoterre.brgm.fr/Notices/0466N.pdf' },
    { sheet: '0467', name: 'QUARRE-LES-TOMBES', url: 'http://ficheinfoterre.brgm.fr/Notices/0467N.pdf' },
    { sheet: '0468', name: 'SEMUR-EN-AUXOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0468N.pdf' },
    { sheet: '0469', name: 'ST-SEINE L\'ABBAYE', url: 'http://ficheinfoterre.brgm.fr/Notices/0469N.pdf' },
    { sheet: '0470', name: 'MIREBEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0470N.pdf' },
    { sheet: '0471', name: 'GRAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0471N.pdf' },
    { sheet: '0472', name: 'GY', url: 'http://ficheinfoterre.brgm.fr/Notices/0472N.pdf' },
    { sheet: '0473', name: 'BAUME-LES-DAMES', url: 'http://ficheinfoterre.brgm.fr/Notices/0473N.pdf' },
    { sheet: '0495', name: 'PREMERY', url: 'http://ficheinfoterre.brgm.fr/Notices/0495N.pdf' },
    { sheet: '0496', name: 'CORBIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0496N.pdf' },
    { sheet: '0497', name: 'SAULIEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0497N.pdf' },
    { sheet: '0498', name: 'POUILLY-EN-AUXOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0498N.pdf' },
    { sheet: '0499', name: 'GEVREY-CHAMBERTIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0499N.pdf' },
    { sheet: '0500', name: 'DIJON', url: 'http://ficheinfoterre.brgm.fr/Notices/0500N.pdf' },
    { sheet: '0501', name: 'PESMES', url: 'http://ficheinfoterre.brgm.fr/Notices/0501N.pdf' },
    { sheet: '0502', name: 'BESANCON', url: 'http://ficheinfoterre.brgm.fr/Notices/0502N.pdf' },
    { sheet: '0503', name: 'VERCEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0503N.pdf' },
    { sheet: '0504', name: 'MAICHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0504N.pdf' },
    { sheet: '0505', name: 'DAMPRICHARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0505N.pdf' },
    { sheet: '0522', name: 'ST-SAULGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0522N.pdf' },
    { sheet: '0523', name: 'CHATEAU-CHINON', url: 'http://ficheinfoterre.brgm.fr/Notices/0523N.pdf' },
    { sheet: '0524', name: 'LUCENAY-L\'EVEQUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0524N.pdf' },
    { sheet: '0525', name: 'EPINAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0525N.pdf' },
    { sheet: '0526', name: 'BEAUNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0526N.pdf' },
    { sheet: '0527', name: 'SEURRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0527N.pdf' },
    { sheet: '0528', name: 'DOLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0528N.pdf' },
    { sheet: '0529', name: 'QUINGEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0529N.pdf' },
    { sheet: '0530', name: 'ORNANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0530N.pdf' },
    { sheet: '0531', name: 'MORTEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0531N.pdf' },
    { sheet: '0549', name: 'DECIZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0549N.pdf' },
    { sheet: '0550', name: 'FOURS', url: 'http://ficheinfoterre.brgm.fr/Notices/0550N.pdf' },
    { sheet: '0551', name: 'AUTUN', url: 'http://ficheinfoterre.brgm.fr/Notices/0551N.pdf' },
    { sheet: '0552', name: 'LE CREUSOT', url: 'http://ficheinfoterre.brgm.fr/Notices/0552N.pdf' },
    { sheet: '0553', name: 'CHAGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0553N.pdf' },
    { sheet: '0554', name: 'PIERRE-DE-BRESSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0554N.pdf' },
    { sheet: '0555', name: 'POLIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0555N.pdf' },
    { sheet: '0556', name: 'SALINS-LES-BAINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0556N.pdf' },
    { sheet: '0557', name: 'PONTARLIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0557N.pdf' },
    { sheet: '0575', name: 'DORNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0575N.pdf' },
    { sheet: '0576', name: 'BOURBON-LANCY', url: 'http://ficheinfoterre.brgm.fr/Notices/0576N.pdf' },
    { sheet: '0577', name: 'TOULON-SUR-ARROUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0577N.pdf' },
    { sheet: '0578', name: 'MONTCEAU-LES-MINES', url: 'http://ficheinfoterre.brgm.fr/Notices/0578N.pdf' },
    { sheet: '0579', name: 'CHALON-SUR-SAONE', url: 'http://ficheinfoterre.brgm.fr/Notices/0579N.pdf' },
    { sheet: '0580', name: 'LOUHANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0580N.pdf' },
    { sheet: '0581', name: 'LONS-LE-SAUNIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0581N.pdf' },
    { sheet: '0582', name: 'CHAMPAGNOLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0582N.pdf' },
    { sheet: '0583', name: 'MOUTHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0583N.pdf' },
    { sheet: '0600', name: 'PARAY-LE-MONIAL', url: 'http://ficheinfoterre.brgm.fr/Notices/0600N.pdf' },
    { sheet: '0601', name: 'ST-BONNET-DE-JOUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0601N.pdf' },
    { sheet: '0602', name: 'TOURNUS', url: 'http://ficheinfoterre.brgm.fr/Notices/0602N.pdf' },
    { sheet: '0603', name: 'MONTPONT-EN-BRESSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0603N.pdf' },
    { sheet: '0604', name: 'ORGELET-LE-BOURGET', url: 'http://ficheinfoterre.brgm.fr/Notices/0604N.pdf' },
    { sheet: '0605', name: 'MOREZ-BOIS D\'AMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0605N.pdf' },
    { sheet: '0625', name: 'MACON', url: 'http://ficheinfoterre.brgm.fr/Notices/0625N.pdf' },
    { sheet: '0626', name: 'ST-AMOUR', url: 'http://ficheinfoterre.brgm.fr/Notices/0626N.pdf' },
    { sheet: '0627', name: 'MOIRANS-EN-MONTAGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0627N.pdf' },
    { sheet: '0628', name: 'ST-CLAUDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0628N.pdf' },
    { sheet: '0629', name: 'DOUVAINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0629N.pdf' },
    { sheet: '0630', name: 'THONON-CHATEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0630N.pdf' },
    { sheet: '0652', name: 'NANTUA', url: 'http://ficheinfoterre.brgm.fr/Notices/0652N.pdf' },
    { sheet: '0653', name: 'ST JULIEN-EN-GENEVOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0653N.pdf' },
    { sheet: '0654', name: 'ANNEMASSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0654N.pdf' },
    { sheet: '0655', name: 'SAMOENS - PAS-DE-MORGINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0655N.pdf' },
  ],
  'bretagne': [
    { sheet: '0170', name: 'PERROS-GUIREC', url: 'http://ficheinfoterre.brgm.fr/Notices/0170N.pdf' },
    { sheet: '0171', name: 'TREGUIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0171N.pdf' },
    { sheet: '0200', name: 'PLOUGUERNEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0200N.pdf' },
    { sheet: '0201', name: 'ST-POL-DE-LEON', url: 'http://ficheinfoterre.brgm.fr/Notices/0201N.pdf' },
    { sheet: '0202', name: 'PLESTIN-LES-GREVES', url: 'http://ficheinfoterre.brgm.fr/Notices/0202N.pdf' },
    { sheet: '0203', name: 'LANNION', url: 'http://ficheinfoterre.brgm.fr/Notices/0203N.pdf' },
    { sheet: '0204', name: 'PONTRIEUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0204N.pdf' },
    { sheet: '0206', name: 'ST-CAST', url: 'http://ficheinfoterre.brgm.fr/Notices/0206N.pdf' },
    { sheet: '0207', name: 'ST-MALO', url: 'http://ficheinfoterre.brgm.fr/Notices/0207N.pdf' },
    { sheet: '0237', name: 'PLOUARZEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0237N.pdf' },
    { sheet: '0238', name: 'PLABENNEC', url: 'http://ficheinfoterre.brgm.fr/Notices/0238N.pdf' },
    { sheet: '0239', name: 'LANDERNEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0239N.pdf' },
    { sheet: '0240', name: 'MORLAIX', url: 'http://ficheinfoterre.brgm.fr/Notices/0240N.pdf' },
    { sheet: '0241', name: 'BELLE-ISLE-EN-TERRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0241N.pdf' },
    { sheet: '0242', name: 'GUINGAMP', url: 'http://ficheinfoterre.brgm.fr/Notices/0242N.pdf' },
    { sheet: '0243', name: 'ST-BRIEUC', url: 'http://ficheinfoterre.brgm.fr/Notices/0243N.pdf' },
    { sheet: '0244', name: 'LAMBALLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0244N.pdf' },
    { sheet: '0245', name: 'DINAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0245N.pdf' },
    { sheet: '0246', name: 'DOL-DE-BRETAGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0246N.pdf' },
    { sheet: '0273', name: 'LE CONQUET', url: 'http://ficheinfoterre.brgm.fr/Notices/0273N.pdf' },
    { sheet: '0274', name: 'BREST', url: 'http://ficheinfoterre.brgm.fr/Notices/0274N.pdf' },
    { sheet: '0275', name: 'LE FAOU', url: 'http://ficheinfoterre.brgm.fr/Notices/0275N.pdf' },
    { sheet: '0276', name: 'HUELGOAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0276N.pdf' },
    { sheet: '0277', name: 'CARHAIX-PLOUGUER', url: 'http://ficheinfoterre.brgm.fr/Notices/0277N.pdf' },
    { sheet: '0278', name: 'QUINTIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0278N.pdf' },
    { sheet: '0279', name: 'MONCONTOUR', url: 'http://ficheinfoterre.brgm.fr/Notices/0279N.pdf' },
    { sheet: '0280', name: 'BROONS', url: 'http://ficheinfoterre.brgm.fr/Notices/0280N.pdf' },
    { sheet: '0281', name: 'CAULNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0281N.pdf' },
    { sheet: '0282', name: 'COMBOURG', url: 'http://ficheinfoterre.brgm.fr/Notices/0282N.pdf' },
    { sheet: '0283', name: 'FOUGERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0283N.pdf' },
    { sheet: '0309', name: 'DOUARNENEZ', url: 'http://ficheinfoterre.brgm.fr/Notices/0309N.pdf' },
    { sheet: '0310', name: 'CHATEAULIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0310N.pdf' },
    { sheet: '0311', name: 'GOURIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0311N.pdf' },
    { sheet: '0312', name: 'ROSTRENEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0312N.pdf' },
    { sheet: '0313', name: 'PONTIVY', url: 'http://ficheinfoterre.brgm.fr/Notices/0313N.pdf' },
    { sheet: '0314', name: 'LOUDEAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0314N.pdf' },
    { sheet: '0315', name: 'ST-MEEN-LE-GRAND', url: 'http://ficheinfoterre.brgm.fr/Notices/0315N.pdf' },
    { sheet: '0316', name: 'MONTFORT-SUR-MEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0316N.pdf' },
    { sheet: '0344', name: 'POINTE DU RAZ', url: 'http://ficheinfoterre.brgm.fr/Notices/0344N.pdf' },
    { sheet: '0345', name: 'PONT-CROIX', url: 'http://ficheinfoterre.brgm.fr/Notices/0345N.pdf' },
    { sheet: '0346', name: 'QUIMPER', url: 'http://ficheinfoterre.brgm.fr/Notices/0346N.pdf' },
    { sheet: '0347', name: 'ROSPORDEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0347N.pdf' },
    { sheet: '0348', name: 'PLOUAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0348N.pdf' },
    { sheet: '0349', name: 'BUBRY', url: 'http://ficheinfoterre.brgm.fr/Notices/0349N.pdf' },
    { sheet: '0350', name: 'JOSSELIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0350N.pdf' },
    { sheet: '0351', name: 'PLOERMEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0351N.pdf' },
    { sheet: '0352', name: 'GUER', url: 'http://ficheinfoterre.brgm.fr/Notices/0352N.pdf' },
    { sheet: '0381', name: 'PONT L\'ABBE PTE DE PENMARCH', url: 'http://ficheinfoterre.brgm.fr/Notices/0381N.pdf' },
    { sheet: '0382', name: 'CONCARNEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0382N.pdf' },
    { sheet: '0383', name: 'LORIENT', url: 'http://ficheinfoterre.brgm.fr/Notices/0383N.pdf' },
    { sheet: '0384', name: 'BAUD', url: 'http://ficheinfoterre.brgm.fr/Notices/0384N.pdf' },
    { sheet: '0385', name: 'ELVEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0385N.pdf' },
    { sheet: '0386', name: 'MALESTROIT', url: 'http://ficheinfoterre.brgm.fr/Notices/0386N.pdf' },
    { sheet: '0387', name: 'PIPRIAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0387N.pdf' },
    { sheet: '0415', name: 'ILE DE GROIX', url: 'http://ficheinfoterre.brgm.fr/Notices/0415N.pdf' },
    { sheet: '0416', name: 'AUARY-QUIBERON', url: 'http://ficheinfoterre.brgm.fr/Notices/0416N.pdf' },
    { sheet: '0417', name: 'VANNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0417N.pdf' },
    { sheet: '0418', name: 'QUESTEMBERT', url: 'http://ficheinfoterre.brgm.fr/Notices/0418N.pdf' },
    { sheet: '0477', name: 'BELLE-ILE-EN-MER ILES HOUAT ET HOEDIC', url: 'http://ficheinfoterre.brgm.fr/Notices/0477N.pdf' },
    { sheet: '0479', name: 'ST-NAZAIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0479N.pdf' },
  ],
  'centre-val-de-loire': [
    { sheet: '0216', name: 'DREUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0216N.pdf' },
    { sheet: '0253', name: 'LA LOUPE', url: 'http://ficheinfoterre.brgm.fr/Notices/0253N.pdf' },
    { sheet: '0254', name: 'COURVILLE SUR EURE', url: 'http://ficheinfoterre.brgm.fr/Notices/0254N.pdf' },
    { sheet: '0289', name: 'NOGENT-LE-RETROU', url: 'http://ficheinfoterre.brgm.fr/Notices/0289N.pdf' },
    { sheet: '0290', name: 'ILLIERS-COMBRAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0290N.pdf' },
    { sheet: '0291', name: 'VOVES', url: 'http://ficheinfoterre.brgm.fr/Notices/0291N.pdf' },
    { sheet: '0323', name: 'LA FERTE-BERNARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0323N.pdf' },
    { sheet: '0324', name: 'AUTHON-DU-PERCHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0324N.pdf' },
    { sheet: '0325', name: 'CHATEAUDUN', url: 'http://ficheinfoterre.brgm.fr/Notices/0325N.pdf' },
    { sheet: '0326', name: 'ORGERES-EN-BEAUCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0326N.pdf' },
    { sheet: '0359', name: 'BOULOIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0359N.pdf' },
    { sheet: '0360', name: 'ST-CALAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0360N.pdf' },
    { sheet: '0361', name: 'CLOYES-SUR-LE-LOIR', url: 'http://ficheinfoterre.brgm.fr/Notices/0361N.pdf' },
    { sheet: '0362', name: 'PATAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0362N.pdf' },
    { sheet: '0363', name: 'ORLEANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0363N.pdf' },
    { sheet: '0364', name: 'BELLEGARDE-DU-LOIRET', url: 'http://ficheinfoterre.brgm.fr/Notices/0364N.pdf' },
    { sheet: '0365', name: 'MONTARGIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0365N.pdf' },
    { sheet: '0366', name: 'COURTENAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0366N.pdf' },
    { sheet: '0394', name: 'LA CHARTRE-SUR-LE-LOIR', url: 'http://ficheinfoterre.brgm.fr/Notices/0394N.pdf' },
    { sheet: '0395', name: 'VENDOME', url: 'http://ficheinfoterre.brgm.fr/Notices/0395N.pdf' },
    { sheet: '0396', name: 'SELOMMES', url: 'http://ficheinfoterre.brgm.fr/Notices/0396N.pdf' },
    { sheet: '0397', name: 'BEAUGENCY', url: 'http://ficheinfoterre.brgm.fr/Notices/0397N.pdf' },
    { sheet: '0398', name: 'LA FERTE-ST-AUBIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0398N.pdf' },
    { sheet: '0399', name: 'CHATEAUNEUF SUR LOIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0399N.pdf' },
    { sheet: '0400', name: 'CHATILLON-COLIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0400N.pdf' },
    { sheet: '0401', name: 'BLENEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0401N.pdf' },
    { sheet: '0426', name: 'CHATEAU-DU-LOIR', url: 'http://ficheinfoterre.brgm.fr/Notices/0426N.pdf' },
    { sheet: '0427', name: 'CHATEAU-RENAULT', url: 'http://ficheinfoterre.brgm.fr/Notices/0427N.pdf' },
    { sheet: '0428', name: 'BLOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0428N.pdf' },
    { sheet: '0429', name: 'BRACIEUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0429N.pdf' },
    { sheet: '0430', name: 'LAMOTTE-BEUVRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0430N.pdf' },
    { sheet: '0431', name: 'ARGENT-SUR-SAULDRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0431N.pdf' },
    { sheet: '0432', name: 'GIEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0432N.pdf' },
    { sheet: '0433', name: 'ST-FARGEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0433N.pdf' },
    { sheet: '0457', name: 'TOURS', url: 'http://ficheinfoterre.brgm.fr/Notices/0457N.pdf' },
    { sheet: '0458', name: 'AMBOISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0458N.pdf' },
    { sheet: '0459', name: 'MONTRICHARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0459N.pdf' },
    { sheet: '0460', name: 'ROMORANTIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0460N.pdf' },
    { sheet: '0461', name: 'SALBRIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0461N.pdf' },
    { sheet: '0462', name: 'AUBIGNY SUR NERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0462N.pdf' },
    { sheet: '0463', name: 'LERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0463N.pdf' },
    { sheet: '0464', name: 'COSNE SUR LOIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0464N.pdf' },
    { sheet: '0487', name: 'LANGEAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0487N.pdf' },
    { sheet: '0488', name: 'BLERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0488N.pdf' },
    { sheet: '0489', name: 'ST-AIGNAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0489N.pdf' },
    { sheet: '0490', name: 'SELLES-SUR-CHER', url: 'http://ficheinfoterre.brgm.fr/Notices/0490N.pdf' },
    { sheet: '0491', name: 'VIERZON', url: 'http://ficheinfoterre.brgm.fr/Notices/0491N.pdf' },
    { sheet: '0492', name: 'ST-MARTIN-D\'AUXIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0492N.pdf' },
    { sheet: '0493', name: 'SANCERRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0493N.pdf' },
    { sheet: '0494', name: 'LA CHARITE', url: 'http://ficheinfoterre.brgm.fr/Notices/0494N.pdf' },
    { sheet: '0514', name: 'STE-MAURE-DE-TOURAINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0514N.pdf' },
    { sheet: '0515', name: 'LOCHES', url: 'http://ficheinfoterre.brgm.fr/Notices/0515N.pdf' },
    { sheet: '0516', name: 'CHATILLON-SUR-INDRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0516N.pdf' },
    { sheet: '0517', name: 'LEVROUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0517N.pdf' },
    { sheet: '0518', name: 'VATAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0518N.pdf' },
    { sheet: '0519', name: 'BOURGES', url: 'http://ficheinfoterre.brgm.fr/Notices/0519N.pdf' },
    { sheet: '0520', name: 'NERONDES', url: 'http://ficheinfoterre.brgm.fr/Notices/0520N.pdf' },
    { sheet: '0521', name: 'NEVERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0521N.pdf' },
    { sheet: '0541', name: 'CHATELLERAULT', url: 'http://ficheinfoterre.brgm.fr/Notices/0541N.pdf' },
    { sheet: '0542', name: 'PREUILLY', url: 'http://ficheinfoterre.brgm.fr/Notices/0542N.pdf' },
    { sheet: '0543', name: 'BUZANCAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0543N.pdf' },
    { sheet: '0544', name: 'CHATEAUROUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0544N.pdf' },
    { sheet: '0545', name: 'ISSOUDUN', url: 'http://ficheinfoterre.brgm.fr/Notices/0545N.pdf' },
    { sheet: '0546', name: 'CHATEAUNEUF-SUR-CHER', url: 'http://ficheinfoterre.brgm.fr/Notices/0546N.pdf' },
    { sheet: '0547', name: 'DUN-SUR-AURON', url: 'http://ficheinfoterre.brgm.fr/Notices/0547N.pdf' },
    { sheet: '0548', name: 'SANCOINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0548N.pdf' },
    { sheet: '0567', name: 'VOUNEUIL-SUR-VIENNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0567N.pdf' },
    { sheet: '0568', name: 'LE BLANC', url: 'http://ficheinfoterre.brgm.fr/Notices/0568N.pdf' },
    { sheet: '0569', name: 'ST-GAULTIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0569N.pdf' },
    { sheet: '0570', name: 'VELLES', url: 'http://ficheinfoterre.brgm.fr/Notices/0570N.pdf' },
    { sheet: '0571', name: 'ARDENTES', url: 'http://ficheinfoterre.brgm.fr/Notices/0571N.pdf' },
    { sheet: '0572', name: 'SAINT AMAND MONTROND', url: 'http://ficheinfoterre.brgm.fr/Notices/0572N.pdf' },
    { sheet: '0573', name: 'CHARENTON DU CHER', url: 'http://ficheinfoterre.brgm.fr/Notices/0573N.pdf' },
    { sheet: '0574', name: 'LURCY-LEVIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0574N.pdf' },
    { sheet: '0590', name: 'CHAUVIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0590N.pdf' },
    { sheet: '0591', name: 'LA TRIMOUILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0591N.pdf' },
    { sheet: '0592', name: 'BELABRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0592N.pdf' },
    { sheet: '0593', name: 'ARGENTON-SUR-CREUSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0593N.pdf' },
    { sheet: '0594', name: 'LA CHATRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0594N.pdf' },
    { sheet: '0595', name: 'CHATEAUMEILLANT', url: 'http://ficheinfoterre.brgm.fr/Notices/0595N.pdf' },
    { sheet: '0596', name: 'HERISSON', url: 'http://ficheinfoterre.brgm.fr/Notices/0596N.pdf' },
    { sheet: '0613', name: 'GENCAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0613N.pdf' },
    { sheet: '0614', name: 'MONTMORILLON', url: 'http://ficheinfoterre.brgm.fr/Notices/0614N.pdf' },
    { sheet: '0615', name: 'SAINT SULPICE LES FEUILLES', url: 'http://ficheinfoterre.brgm.fr/Notices/0615N.pdf' },
    { sheet: '0616', name: 'DUN-LE-PALESTEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0616N.pdf' },
    { sheet: '0617', name: 'AIGURANDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0617N.pdf' },
    { sheet: '0618', name: 'BOUSSAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0618N.pdf' },
    { sheet: '0619', name: 'MONTLUCON', url: 'http://ficheinfoterre.brgm.fr/Notices/0619N.pdf' },
  ],
  'corse': [
    { sheet: '1103', name: 'ST-FLORENT', url: 'http://ficheinfoterre.brgm.fr/Notices/1103N.pdf' },
    { sheet: '1110', name: 'CORTE', url: 'http://ficheinfoterre.brgm.fr/Notices/1110N.pdf' },
    { sheet: '1117', name: 'SARROLA-CARCOPINO', url: 'http://ficheinfoterre.brgm.fr/Notices/1117N.pdf' },
    { sheet: '1118', name: 'BASTELICA', url: 'http://ficheinfoterre.brgm.fr/Notices/1118N.pdf' },
    { sheet: '1119', name: 'GHISONACCIA', url: 'http://ficheinfoterre.brgm.fr/Notices/1119N.pdf' },
    { sheet: '1120', name: 'AJACCIO', url: 'http://ficheinfoterre.brgm.fr/Notices/1120N.pdf' },
    { sheet: '1121', name: 'ZICAVO', url: 'http://ficheinfoterre.brgm.fr/Notices/1121N.pdf' },
  ],
  'grand-est': [
    { sheet: '0040', name: 'GIVET', url: 'http://ficheinfoterre.brgm.fr/Notices/0040N.pdf' },
    { sheet: '0052', name: 'ROCROI', url: 'http://ficheinfoterre.brgm.fr/Notices/0052N.pdf' },
    { sheet: '0053', name: 'FUMAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0053N.pdf' },
    { sheet: '0068', name: 'RENWEZ', url: 'http://ficheinfoterre.brgm.fr/Notices/0068N.pdf' },
    { sheet: '0069', name: 'CHARLEVILLE-MEZIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0069N.pdf' },
    { sheet: '0086', name: 'RETHEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0086N.pdf' },
    { sheet: '0087', name: 'RAUCOURT-ET-FLABA', url: 'http://ficheinfoterre.brgm.fr/Notices/0087N.pdf' },
    { sheet: '0088', name: 'MONTMEDY-FRANCHEVAL', url: 'http://ficheinfoterre.brgm.fr/Notices/0088N.pdf' },
    { sheet: '0109', name: 'ATTIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0109N.pdf' },
    { sheet: '0110', name: 'VOUZIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0110N.pdf' },
    { sheet: '0111', name: 'STENAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0111N.pdf' },
    { sheet: '0112', name: 'LONGUYON-GORCY', url: 'http://ficheinfoterre.brgm.fr/Notices/0112N.pdf' },
    { sheet: '0113', name: 'LONGWY - AUDUN-LE-ROMAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0113N.pdf' },
    { sheet: '0114', name: 'THIONVILLE - WALDWISSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0114N.pdf' },
    { sheet: '0133', name: 'MOURMELON-LE-GRAND', url: 'http://ficheinfoterre.brgm.fr/Notices/0133N.pdf' },
    { sheet: '0134', name: 'MONTHOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0134N.pdf' },
    { sheet: '0135', name: 'VERDUN', url: 'http://ficheinfoterre.brgm.fr/Notices/0135N.pdf' },
    { sheet: '0136', name: 'ETAIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0136N.pdf' },
    { sheet: '0137', name: 'BRIEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0137N.pdf' },
    { sheet: '0138', name: 'UCKANGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0138N.pdf' },
    { sheet: '0139', name: 'BOULAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0139N.pdf' },
    { sheet: '0140', name: 'FORBACH', url: 'http://ficheinfoterre.brgm.fr/Notices/0140N.pdf' },
    { sheet: '0159', name: 'SUIPPES', url: 'http://ficheinfoterre.brgm.fr/Notices/0159N.pdf' },
    { sheet: '0160', name: 'STE-MENEHOULD', url: 'http://ficheinfoterre.brgm.fr/Notices/0160N.pdf' },
    { sheet: '0161', name: 'CLERMONT-EN-ARGONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0161N.pdf' },
    { sheet: '0162', name: 'VIGNEULLES-LES-HATTONCHATEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0162N.pdf' },
    { sheet: '0163', name: 'CHAMBLEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0163N.pdf' },
    { sheet: '0164', name: 'METZ', url: 'http://ficheinfoterre.brgm.fr/Notices/0164N.pdf' },
    { sheet: '0165', name: 'ST-AVOLD', url: 'http://ficheinfoterre.brgm.fr/Notices/0165N.pdf' },
    { sheet: '0166', name: 'SARREGUEMINES', url: 'http://ficheinfoterre.brgm.fr/Notices/0166N.pdf' },
    { sheet: '0167', name: 'BITCHE-WALSCHBRONN', url: 'http://ficheinfoterre.brgm.fr/Notices/0167N.pdf' },
    { sheet: '0168', name: 'LEMBACH', url: 'http://ficheinfoterre.brgm.fr/Notices/0168N.pdf' },
    { sheet: '0188', name: 'VERTUS', url: 'http://ficheinfoterre.brgm.fr/Notices/0188N.pdf' },
    { sheet: '0189', name: 'CHALONS-SUR-MARNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0189N.pdf' },
    { sheet: '0190', name: 'REVIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0190N.pdf' },
    { sheet: '0191', name: 'VAUBECOURT', url: 'http://ficheinfoterre.brgm.fr/Notices/0191N.pdf' },
    { sheet: '0192', name: 'ST-MIHIEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0192N.pdf' },
    { sheet: '0193', name: 'PONT-A -MOUSSON', url: 'http://ficheinfoterre.brgm.fr/Notices/0193N.pdf' },
    { sheet: '0194', name: 'NOMENY', url: 'http://ficheinfoterre.brgm.fr/Notices/0194N.pdf' },
    { sheet: '0195', name: 'CHATEAU-SALINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0195N.pdf' },
    { sheet: '0196', name: 'SARRE-UNION', url: 'http://ficheinfoterre.brgm.fr/Notices/0196N.pdf' },
    { sheet: '0197', name: 'BOUXWILLER', url: 'http://ficheinfoterre.brgm.fr/Notices/0197N.pdf' },
    { sheet: '0198', name: 'HAGUENAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0198N.pdf' },
    { sheet: '0199', name: 'SELTZ', url: 'http://ficheinfoterre.brgm.fr/Notices/0199N.pdf' },
    { sheet: '0223', name: 'SEZANNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0223N.pdf' },
    { sheet: '0224', name: 'FERE-CHAMPENOISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0224N.pdf' },
    { sheet: '0225', name: 'VITRY-LE-FRANCOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0225N.pdf' },
    { sheet: '0226', name: 'ST-DIZIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0226N.pdf' },
    { sheet: '0227', name: 'BAR-LE-DUC', url: 'http://ficheinfoterre.brgm.fr/Notices/0227N.pdf' },
    { sheet: '0228', name: 'COMMERCY', url: 'http://ficheinfoterre.brgm.fr/Notices/0228N.pdf' },
    { sheet: '0229', name: 'TOUL', url: 'http://ficheinfoterre.brgm.fr/Notices/0229N.pdf' },
    { sheet: '0230', name: 'NANCY', url: 'http://ficheinfoterre.brgm.fr/Notices/0230N.pdf' },
    { sheet: '0231', name: 'PARROY', url: 'http://ficheinfoterre.brgm.fr/Notices/0231N.pdf' },
    { sheet: '0232', name: 'SARREBOURG', url: 'http://ficheinfoterre.brgm.fr/Notices/0232N.pdf' },
    { sheet: '0233', name: 'SAVERNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0233N.pdf' },
    { sheet: '0234', name: 'BRUMATH', url: 'http://ficheinfoterre.brgm.fr/Notices/0234N.pdf' },
    { sheet: '0261', name: 'ROMILLY-SUR-SEINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0261N.pdf' },
    { sheet: '0262', name: 'ARCIS-SUR-AUBE', url: 'http://ficheinfoterre.brgm.fr/Notices/0262N.pdf' },
    { sheet: '0263', name: 'CHAVANGES', url: 'http://ficheinfoterre.brgm.fr/Notices/0263N.pdf' },
    { sheet: '0264', name: 'WASSY', url: 'http://ficheinfoterre.brgm.fr/Notices/0264N.pdf' },
    { sheet: '0265', name: 'JOINVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0265N.pdf' },
    { sheet: '0266', name: 'GONDRECOURT-LE-CHATEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0266N.pdf' },
    { sheet: '0267', name: 'VEZELISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0267N.pdf' },
    { sheet: '0268', name: 'BAYON', url: 'http://ficheinfoterre.brgm.fr/Notices/0268N.pdf' },
    { sheet: '0269', name: 'LUNEVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0269N.pdf' },
    { sheet: '0270', name: 'CIREY-SUR-VEZOUZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0270N.pdf' },
    { sheet: '0271', name: 'MOLSHEIM', url: 'http://ficheinfoterre.brgm.fr/Notices/0271N.pdf' },
    { sheet: '0272', name: 'STRASBOURG', url: 'http://ficheinfoterre.brgm.fr/Notices/0272N.pdf' },
    { sheet: '0297', name: 'ESTISSAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0297N.pdf' },
    { sheet: '0298', name: 'TROYES', url: 'http://ficheinfoterre.brgm.fr/Notices/0298N.pdf' },
    { sheet: '0299', name: 'BRIENNE-LE-CHATEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0299N.pdf' },
    { sheet: '0300', name: 'DOULEVANT-LE-CHATEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0300N.pdf' },
    { sheet: '0301', name: 'DOULAINCOURT', url: 'http://ficheinfoterre.brgm.fr/Notices/0301N.pdf' },
    { sheet: '0302', name: 'NEUFCHATEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0302N.pdf' },
    { sheet: '0303', name: 'CHATENOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0303N.pdf' },
    { sheet: '0304', name: 'MIRECOURT', url: 'http://ficheinfoterre.brgm.fr/Notices/0304N.pdf' },
    { sheet: '0305', name: 'RAMBERVILLERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0305N.pdf' },
    { sheet: '0306', name: 'ST-DIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0306N.pdf' },
    { sheet: '0307', name: 'SELESTAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0307N.pdf' },
    { sheet: '0308', name: 'BENFELD', url: 'http://ficheinfoterre.brgm.fr/Notices/0308N.pdf' },
    { sheet: '0332', name: 'AIX-EN-OTHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0332N.pdf' },
    { sheet: '0333', name: 'BOUILLY', url: 'http://ficheinfoterre.brgm.fr/Notices/0333N.pdf' },
    { sheet: '0334', name: 'BAR-SUR-SEINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0334N.pdf' },
    { sheet: '0335', name: 'BAR-SUR-AUBE', url: 'http://ficheinfoterre.brgm.fr/Notices/0335N.pdf' },
    { sheet: '0336', name: 'CHAUMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0336N.pdf' },
    { sheet: '0337', name: 'BOURMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0337N.pdf' },
    { sheet: '0338', name: 'VITTEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0338N.pdf' },
    { sheet: '0339', name: 'EPINAL', url: 'http://ficheinfoterre.brgm.fr/Notices/0339N.pdf' },
    { sheet: '0340', name: 'BRUYERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0340N.pdf' },
    { sheet: '0341', name: 'GERARDMER', url: 'http://ficheinfoterre.brgm.fr/Notices/0341N.pdf' },
    { sheet: '0342', name: 'COLMAR-ARTOLSHEIM', url: 'http://ficheinfoterre.brgm.fr/Notices/0342N.pdf' },
    { sheet: '0371', name: 'CHATEAUVILLAIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0371N.pdf' },
    { sheet: '0372', name: 'NOGENT-EN-BASSIGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0372N.pdf' },
    { sheet: '0373', name: 'BOURBONNE-LES-BAINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0373N.pdf' },
    { sheet: '0374', name: 'MONTHUREUX-SUR-SAONE', url: 'http://ficheinfoterre.brgm.fr/Notices/0374N.pdf' },
    { sheet: '0375', name: 'PLOMBIERES-LES-BAINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0375N.pdf' },
    { sheet: '0376', name: 'REMIREMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0376N.pdf' },
    { sheet: '0377', name: 'MUNSTER', url: 'http://ficheinfoterre.brgm.fr/Notices/0377N.pdf' },
    { sheet: '0378', name: 'NEUF-BRISACH', url: 'http://ficheinfoterre.brgm.fr/Notices/0378N.pdf' },
    { sheet: '0407', name: 'LANGRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0407N.pdf' },
    { sheet: '0408', name: 'FAYL-BILLOT', url: 'http://ficheinfoterre.brgm.fr/Notices/0408N.pdf' },
    { sheet: '0409', name: 'JUSSEY', url: 'http://ficheinfoterre.brgm.fr/Notices/0409N.pdf' },
    { sheet: '0410', name: 'LUXEUIL-LES-BAINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0410N.pdf' },
    { sheet: '0411', name: 'GIROMAGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0411N.pdf' },
    { sheet: '0412', name: 'THANN', url: 'http://ficheinfoterre.brgm.fr/Notices/0412N.pdf' },
    { sheet: '0413', name: 'MULHOUSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0413N.pdf' },
    { sheet: '0442', name: 'VESOUL', url: 'http://ficheinfoterre.brgm.fr/Notices/0442N.pdf' },
    { sheet: '0443', name: 'LURE', url: 'http://ficheinfoterre.brgm.fr/Notices/0443N.pdf' },
    { sheet: '0444', name: 'BELFORT', url: 'http://ficheinfoterre.brgm.fr/Notices/0444N.pdf' },
    { sheet: '0445', name: 'ALTKIRCH-HUNINGUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0445N.pdf' },
    { sheet: '0474', name: 'MONTBELIARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0474N.pdf' },
    { sheet: '0475', name: 'DELLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0475N.pdf' },
    { sheet: '0476', name: 'FERRETTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0476N.pdf' },
  ],
  'hauts-de-france': [
    { sheet: '0002', name: 'CALAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0002N.pdf' },
    { sheet: '0003', name: 'DUNKERQUE-HONDSCHOOTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0003N.pdf' },
    { sheet: '0005', name: 'MARQUISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0005N.pdf' },
    { sheet: '0006', name: 'GUINES', url: 'http://ficheinfoterre.brgm.fr/Notices/0006N.pdf' },
    { sheet: '0007', name: 'CASSEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0007N.pdf' },
    { sheet: '0008', name: 'STEENVOORDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0008N.pdf' },
    { sheet: '0010', name: 'BOULOGNE-SUR-MER', url: 'http://ficheinfoterre.brgm.fr/Notices/0010N.pdf' },
    { sheet: '0011', name: 'DESVRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0011N.pdf' },
    { sheet: '0012', name: 'SAINT-OMER', url: 'http://ficheinfoterre.brgm.fr/Notices/0012N.pdf' },
    { sheet: '0013', name: 'HAZEBROUCK', url: 'http://ficheinfoterre.brgm.fr/Notices/0013N.pdf' },
    { sheet: '0014', name: 'LILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0014N.pdf' },
    { sheet: '0016', name: 'MONTREUIL', url: 'http://ficheinfoterre.brgm.fr/Notices/0016N.pdf' },
    { sheet: '0017', name: 'FRUGES', url: 'http://ficheinfoterre.brgm.fr/Notices/0017N.pdf' },
    { sheet: '0018', name: 'LILLERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0018N.pdf' },
    { sheet: '0019', name: 'BETHUNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0019N.pdf' },
    { sheet: '0020', name: 'CARVIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0020N.pdf' },
    { sheet: '0021', name: 'ST-AMAND-CRESPIN-MONS', url: 'http://ficheinfoterre.brgm.fr/Notices/0021N.pdf' },
    { sheet: '0023', name: 'RUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0023N.pdf' },
    { sheet: '0024', name: 'HESDIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0024N.pdf' },
    { sheet: '0025', name: 'SAINT-POL', url: 'http://ficheinfoterre.brgm.fr/Notices/0025N.pdf' },
    { sheet: '0026', name: 'ARRAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0026N.pdf' },
    { sheet: '0027', name: 'DOUAI', url: 'http://ficheinfoterre.brgm.fr/Notices/0027N.pdf' },
    { sheet: '0028', name: 'VALENCIENNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0028N.pdf' },
    { sheet: '0029', name: 'LE QUESNOY', url: 'http://ficheinfoterre.brgm.fr/Notices/0029N.pdf' },
    { sheet: '0030', name: 'MAUBEUGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0030N.pdf' },
    { sheet: '0032', name: 'ST-VALERY-SUR-SOMME EU', url: 'http://ficheinfoterre.brgm.fr/Notices/0032N.pdf' },
    { sheet: '0033', name: 'ABBEVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0033N.pdf' },
    { sheet: '0034', name: 'DOULLENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0034N.pdf' },
    { sheet: '0035', name: 'BAPAUME', url: 'http://ficheinfoterre.brgm.fr/Notices/0035N.pdf' },
    { sheet: '0036', name: 'CAMBRAI', url: 'http://ficheinfoterre.brgm.fr/Notices/0036N.pdf' },
    { sheet: '0037', name: 'LE CATEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0037N.pdf' },
    { sheet: '0038', name: 'AVESNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0038N.pdf' },
    { sheet: '0039', name: 'TRELON', url: 'http://ficheinfoterre.brgm.fr/Notices/0039N.pdf' },
    { sheet: '0044', name: 'GAMACHES', url: 'http://ficheinfoterre.brgm.fr/Notices/0044N.pdf' },
    { sheet: '0045', name: 'HALLENCOURT', url: 'http://ficheinfoterre.brgm.fr/Notices/0045N.pdf' },
    { sheet: '0046', name: 'AMIENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0046N.pdf' },
    { sheet: '0047', name: 'ALBERT', url: 'http://ficheinfoterre.brgm.fr/Notices/0047N.pdf' },
    { sheet: '0048', name: 'PERONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0048N.pdf' },
    { sheet: '0049', name: 'BOHAIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0049N.pdf' },
    { sheet: '0050', name: 'GUISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0050N.pdf' },
    { sheet: '0051', name: 'HIRSON', url: 'http://ficheinfoterre.brgm.fr/Notices/0051N.pdf' },
    { sheet: '0060', name: 'NEUFCHATEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0060N.pdf' },
    { sheet: '0061', name: 'POIX', url: 'http://ficheinfoterre.brgm.fr/Notices/0061N.pdf' },
    { sheet: '0062', name: 'MOREUIL', url: 'http://ficheinfoterre.brgm.fr/Notices/0062N.pdf' },
    { sheet: '0063', name: 'ROYE', url: 'http://ficheinfoterre.brgm.fr/Notices/0063N.pdf' },
    { sheet: '0064', name: 'HAM', url: 'http://ficheinfoterre.brgm.fr/Notices/0064N.pdf' },
    { sheet: '0065', name: 'ST-QUENTIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0065N.pdf' },
    { sheet: '0066', name: 'VERVINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0066N.pdf' },
    { sheet: '0067', name: 'ROZOY-SUR-SERRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0067N.pdf' },
    { sheet: '0078', name: 'FORGES-LES-EAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0078N.pdf' },
    { sheet: '0079', name: 'CREVECOEUR-LE-GRAND', url: 'http://ficheinfoterre.brgm.fr/Notices/0079N.pdf' },
    { sheet: '0080', name: 'ST-JUST-EN-CHAUSSEE', url: 'http://ficheinfoterre.brgm.fr/Notices/0080N.pdf' },
    { sheet: '0081', name: 'MONTDIDIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0081N.pdf' },
    { sheet: '0082', name: 'CHAUNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0082N.pdf' },
    { sheet: '0083', name: 'LA FERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0083N.pdf' },
    { sheet: '0084', name: 'LAON', url: 'http://ficheinfoterre.brgm.fr/Notices/0084N.pdf' },
    { sheet: '0085', name: 'CHATEAU-PORCIEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0085N.pdf' },
    { sheet: '0101', name: 'GOURNAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0101N.pdf' },
    { sheet: '0102', name: 'BEAUVAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0102N.pdf' },
    { sheet: '0103', name: 'CLERMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0103N.pdf' },
    { sheet: '0104', name: 'COMPIEGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0104N.pdf' },
    { sheet: '0105', name: 'ATTICHY', url: 'http://ficheinfoterre.brgm.fr/Notices/0105N.pdf' },
    { sheet: '0106', name: 'SOISSONS', url: 'http://ficheinfoterre.brgm.fr/Notices/0106N.pdf' },
    { sheet: '0107', name: 'CRAONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0107N.pdf' },
    { sheet: '0108', name: 'ASFELD', url: 'http://ficheinfoterre.brgm.fr/Notices/0108N.pdf' },
    { sheet: '0129', name: 'VILLERS-COTTERETS', url: 'http://ficheinfoterre.brgm.fr/Notices/0129N.pdf' },
    { sheet: '0130', name: 'FERE-EN-TARDENOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0130N.pdf' },
    { sheet: '0131', name: 'FISMES', url: 'http://ficheinfoterre.brgm.fr/Notices/0131N.pdf' },
    { sheet: '0132', name: 'REIMS', url: 'http://ficheinfoterre.brgm.fr/Notices/0132N.pdf' },
    { sheet: '0157', name: 'EPERNAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0157N.pdf' },
    { sheet: '0158', name: 'AVIZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0158N.pdf' },
    { sheet: '0187', name: 'MONTMORT', url: 'http://ficheinfoterre.brgm.fr/Notices/0187N.pdf' },
  ],
  'ile-de-france': [
    { sheet: '0125', name: 'GISORS', url: 'http://ficheinfoterre.brgm.fr/Notices/0125N.pdf' },
    { sheet: '0126', name: 'MERU', url: 'http://ficheinfoterre.brgm.fr/Notices/0126N.pdf' },
    { sheet: '0127', name: 'CREIL', url: 'http://ficheinfoterre.brgm.fr/Notices/0127N.pdf' },
    { sheet: '0128', name: 'SENLIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0128N.pdf' },
    { sheet: '0151', name: 'MANTES-LA-JOLIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0151N.pdf' },
    { sheet: '0152', name: 'PONTOISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0152N.pdf' },
    { sheet: '0153', name: 'L\'ISLE-ADAM', url: 'http://ficheinfoterre.brgm.fr/Notices/0153N.pdf' },
    { sheet: '0154', name: 'DAMMARTIN-EN-GOELE', url: 'http://ficheinfoterre.brgm.fr/Notices/0154N.pdf' },
    { sheet: '0155', name: 'MEAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0155N.pdf' },
    { sheet: '0156', name: 'CHATEAU-THIERRY', url: 'http://ficheinfoterre.brgm.fr/Notices/0156N.pdf' },
    { sheet: '0181', name: 'HOUDAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0181N.pdf' },
    { sheet: '0182', name: 'VERSAILLES', url: 'http://ficheinfoterre.brgm.fr/Notices/0182N.pdf' },
    { sheet: '0183', name: 'PARIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0183N.pdf' },
    { sheet: '0184', name: 'LAGNY', url: 'http://ficheinfoterre.brgm.fr/Notices/0184N.pdf' },
    { sheet: '0185', name: 'COULOMMIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0185N.pdf' },
    { sheet: '0186', name: 'MONTMIRAIL', url: 'http://ficheinfoterre.brgm.fr/Notices/0186N.pdf' },
    { sheet: '0217', name: 'NOGENT-LE-ROI', url: 'http://ficheinfoterre.brgm.fr/Notices/0217N.pdf' },
    { sheet: '0218', name: 'RAMBOUILLET', url: 'http://ficheinfoterre.brgm.fr/Notices/0218N.pdf' },
    { sheet: '0219', name: 'CORBEIL-ESSONNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0219N.pdf' },
    { sheet: '0220', name: 'BRIE-COMTE-ROBERT', url: 'http://ficheinfoterre.brgm.fr/Notices/0220N.pdf' },
    { sheet: '0221', name: 'ROZAY-EN-BRIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0221N.pdf' },
    { sheet: '0222', name: 'ESTERNAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0222N.pdf' },
    { sheet: '0255', name: 'CHARTRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0255N.pdf' },
    { sheet: '0256', name: 'DOURDAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0256N.pdf' },
    { sheet: '0257', name: 'ETAMPES', url: 'http://ficheinfoterre.brgm.fr/Notices/0257N.pdf' },
    { sheet: '0258', name: 'MELUN', url: 'http://ficheinfoterre.brgm.fr/Notices/0258N.pdf' },
    { sheet: '0259', name: 'NANGIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0259N.pdf' },
    { sheet: '0260', name: 'PROVINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0260N.pdf' },
    { sheet: '0292', name: 'MEREVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0292N.pdf' },
    { sheet: '0293', name: 'MALESHERBES', url: 'http://ficheinfoterre.brgm.fr/Notices/0293N.pdf' },
    { sheet: '0294', name: 'FONTAINEBLEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0294N.pdf' },
    { sheet: '0295', name: 'MONTEREAU-FAUT-YONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0295N.pdf' },
    { sheet: '0296', name: 'SERGINES', url: 'http://ficheinfoterre.brgm.fr/Notices/0296N.pdf' },
    { sheet: '0327', name: 'NEUVILLE-AUX-BOIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0327N.pdf' },
    { sheet: '0328', name: 'PITHIVIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0328N.pdf' },
    { sheet: '0329', name: 'CHATEAU-LANDON', url: 'http://ficheinfoterre.brgm.fr/Notices/0329N.pdf' },
    { sheet: '0330', name: 'CHEROY', url: 'http://ficheinfoterre.brgm.fr/Notices/0330N.pdf' },
    { sheet: '0331', name: 'SENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0331N.pdf' },
  ],
  'normandie': [
    { sheet: '0057', name: 'FECAMP', url: 'http://ficheinfoterre.brgm.fr/Notices/0057N.pdf' },
    { sheet: '0058', name: 'DOUDEVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0058N.pdf' },
    { sheet: '0059', name: 'LONDINIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0059N.pdf' },
    { sheet: '0072', name: 'CHERBOURG', url: 'http://ficheinfoterre.brgm.fr/Notices/0072N.pdf' },
    { sheet: '0073', name: 'SAINT-VAAST-LA-HOUGUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0073N.pdf' },
    { sheet: '0074', name: 'MONTIVILLIERS-ETRETAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0074N.pdf' },
    { sheet: '0075', name: 'BOLBEC', url: 'http://ficheinfoterre.brgm.fr/Notices/0075N.pdf' },
    { sheet: '0076', name: 'YVETOT', url: 'http://ficheinfoterre.brgm.fr/Notices/0076N.pdf' },
    { sheet: '0077', name: 'ST-SAENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0077N.pdf' },
    { sheet: '0093', name: 'BRICQUEBEC', url: 'http://ficheinfoterre.brgm.fr/Notices/0093N.pdf' },
    { sheet: '0094', name: 'SAINTE-MERE-EGLISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0094N.pdf' },
    { sheet: '0095', name: 'GRANDCAMP-MAISY', url: 'http://ficheinfoterre.brgm.fr/Notices/0095N.pdf' },
    { sheet: '0097', name: 'LE HAVRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0097N.pdf' },
    { sheet: '0098', name: 'PONT-AUDEMER', url: 'http://ficheinfoterre.brgm.fr/Notices/0098N.pdf' },
    { sheet: '0099', name: 'ROUEN-OUEST', url: 'http://ficheinfoterre.brgm.fr/Notices/0099N.pdf' },
    { sheet: '0100', name: 'ROUEN-EST', url: 'http://ficheinfoterre.brgm.fr/Notices/0100N.pdf' },
    { sheet: '0116', name: 'LA HAYE-DU-PUITS', url: 'http://ficheinfoterre.brgm.fr/Notices/0116N.pdf' },
    { sheet: '0117', name: 'CARENTAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0117N.pdf' },
    { sheet: '0118', name: 'BALLEROY', url: 'http://ficheinfoterre.brgm.fr/Notices/0118N.pdf' },
    { sheet: '0119', name: 'BAYEUX-COURSEULLES-SUR-MER', url: 'http://ficheinfoterre.brgm.fr/Notices/0119N.pdf' },
    { sheet: '0120', name: 'CAEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0120N.pdf' },
    { sheet: '0121', name: 'LISIEUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0121N.pdf' },
    { sheet: '0122', name: 'BRIONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0122N.pdf' },
    { sheet: '0123', name: 'ELBEUF', url: 'http://ficheinfoterre.brgm.fr/Notices/0123N.pdf' },
    { sheet: '0124', name: 'LES ANDELYS', url: 'http://ficheinfoterre.brgm.fr/Notices/0124N.pdf' },
    { sheet: '0142', name: 'COUTANCES', url: 'http://ficheinfoterre.brgm.fr/Notices/0142N.pdf' },
    { sheet: '0143', name: 'ST-LO', url: 'http://ficheinfoterre.brgm.fr/Notices/0143N.pdf' },
    { sheet: '0144', name: 'TORIGNI-SUR-VIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0144N.pdf' },
    { sheet: '0145', name: 'VILLERS-BOCAGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0145N.pdf' },
    { sheet: '0146', name: 'MEZIDON', url: 'http://ficheinfoterre.brgm.fr/Notices/0146N.pdf' },
    { sheet: '0147', name: 'LIVAROT', url: 'http://ficheinfoterre.brgm.fr/Notices/0147N.pdf' },
    { sheet: '0148', name: 'BERNAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0148N.pdf' },
    { sheet: '0149', name: 'BEAUMONT-LE-ROGER', url: 'http://ficheinfoterre.brgm.fr/Notices/0149N.pdf' },
    { sheet: '0150', name: 'EVREUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0150N.pdf' },
    { sheet: '0172', name: 'GRANVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0172N.pdf' },
    { sheet: '0173', name: 'VILLEDIEU-LES-POELES', url: 'http://ficheinfoterre.brgm.fr/Notices/0173N.pdf' },
    { sheet: '0174', name: 'VIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0174N.pdf' },
    { sheet: '0175', name: 'CONDE-SUR-NOIREAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0175N.pdf' },
    { sheet: '0176', name: 'FALAISE', url: 'http://ficheinfoterre.brgm.fr/Notices/0176N.pdf' },
    { sheet: '0177', name: 'VIMOUTIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0177N.pdf' },
    { sheet: '0178', name: 'RUGLES', url: 'http://ficheinfoterre.brgm.fr/Notices/0178N.pdf' },
    { sheet: '0179', name: 'BRETEUIL-SUR-ITON', url: 'http://ficheinfoterre.brgm.fr/Notices/0179N.pdf' },
    { sheet: '0180', name: 'SAINT-ANDRE-DE-L\'EURE', url: 'http://ficheinfoterre.brgm.fr/Notices/0180N.pdf' },
    { sheet: '0208', name: 'BAIE DU MONT-ST-MICHEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0208N.pdf' },
    { sheet: '0209', name: 'AVRANCHES', url: 'http://ficheinfoterre.brgm.fr/Notices/0209N.pdf' },
    { sheet: '0210', name: 'MORTAIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0210N.pdf' },
    { sheet: '0211', name: 'FLERS-DE-L\'ORNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0211N.pdf' },
    { sheet: '0212', name: 'ARGENTAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0212N.pdf' },
    { sheet: '0213', name: 'SEES', url: 'http://ficheinfoterre.brgm.fr/Notices/0213N.pdf' },
    { sheet: '0214', name: 'L\'AIGLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0214N.pdf' },
    { sheet: '0215', name: 'VERNEUIL', url: 'http://ficheinfoterre.brgm.fr/Notices/0215N.pdf' },
    { sheet: '0247', name: 'SAINT-HILAIRE-DU-HARCOUET', url: 'http://ficheinfoterre.brgm.fr/Notices/0247N.pdf' },
    { sheet: '0249', name: 'DOMFRONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0249N.pdf' },
    { sheet: '0250', name: 'LA FERTE-MACE', url: 'http://ficheinfoterre.brgm.fr/Notices/0250N.pdf' },
    { sheet: '0251', name: 'ALENCON', url: 'http://ficheinfoterre.brgm.fr/Notices/0251N.pdf' },
    { sheet: '0252', name: 'MORTAGNE-AU-PERCHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0252N.pdf' },
  ],
  'nouvelle-aquitaine': [
    { sheet: '0633', name: 'LA ROCHELLE - ILE-DE-RE', url: 'http://ficheinfoterre.brgm.fr/Notices/0633N.pdf' },
    { sheet: '0634', name: 'SURGERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0634N.pdf' },
    { sheet: '0635', name: 'MAUZE-SUR-LE-MIGNON', url: 'http://ficheinfoterre.brgm.fr/Notices/0635N.pdf' },
    { sheet: '0636', name: 'MELLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0636N.pdf' },
    { sheet: '0637', name: 'CIVRAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0637N.pdf' },
    { sheet: '0638', name: 'L\'ISLE-JOURDAIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0638N.pdf' },
    { sheet: '0639', name: 'BELLAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0639N.pdf' },
    { sheet: '0640', name: 'MAGNAC-LAVAL', url: 'http://ficheinfoterre.brgm.fr/Notices/0640N.pdf' },
    { sheet: '0641', name: 'LA SOUTERRAINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0641N.pdf' },
    { sheet: '0642', name: 'GUERET', url: 'http://ficheinfoterre.brgm.fr/Notices/0642N.pdf' },
    { sheet: '0657', name: 'ILE D\'OLERON', url: 'http://ficheinfoterre.brgm.fr/Notices/0657N.pdf' },
    { sheet: '0658', name: 'ROCHEFORT', url: 'http://ficheinfoterre.brgm.fr/Notices/0658N.pdf' },
    { sheet: '0659', name: 'ST-JEAN-D\'ANGELY', url: 'http://ficheinfoterre.brgm.fr/Notices/0659N.pdf' },
    { sheet: '0660', name: 'AULNAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0660N.pdf' },
    { sheet: '0661', name: 'RUFFEC', url: 'http://ficheinfoterre.brgm.fr/Notices/0661N.pdf' },
    { sheet: '0662', name: 'CONFOLENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0662N.pdf' },
    { sheet: '0663', name: 'ORADOUR SUR GLANE', url: 'http://ficheinfoterre.brgm.fr/Notices/0663N.pdf' },
    { sheet: '0664', name: 'AMBAZAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0664N.pdf' },
    { sheet: '0665', name: 'BOURGANEUF', url: 'http://ficheinfoterre.brgm.fr/Notices/0665N.pdf' },
    { sheet: '0666', name: 'ST-SULPICE-LES-CHAMPS', url: 'http://ficheinfoterre.brgm.fr/Notices/0666N.pdf' },
    { sheet: '0681', name: 'MARENNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0681N.pdf' },
    { sheet: '0682', name: 'ST-AGNANT', url: 'http://ficheinfoterre.brgm.fr/Notices/0682N.pdf' },
    { sheet: '0683', name: 'SAINTES', url: 'http://ficheinfoterre.brgm.fr/Notices/0683N.pdf' },
    { sheet: '0684', name: 'MATHA', url: 'http://ficheinfoterre.brgm.fr/Notices/0684N.pdf' },
    { sheet: '0685', name: 'MANSLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0685N.pdf' },
    { sheet: '0686', name: 'LA ROCHEFOUCAULD', url: 'http://ficheinfoterre.brgm.fr/Notices/0686N.pdf' },
    { sheet: '0687', name: 'ROCHECHOUART', url: 'http://ficheinfoterre.brgm.fr/Notices/0687N.pdf' },
    { sheet: '0688', name: 'LIMOGES', url: 'http://ficheinfoterre.brgm.fr/Notices/0688N.pdf' },
    { sheet: '0689', name: 'ST-LEONARD-DE-NOBLAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0689N.pdf' },
    { sheet: '0690', name: 'ROYERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0690N.pdf' },
    { sheet: '0691', name: 'FELLETIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0691N.pdf' },
    { sheet: '0706', name: 'ROYAN - TOUR-DE-CORDOUAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0706N.pdf' },
    { sheet: '0707', name: 'PONS', url: 'http://ficheinfoterre.brgm.fr/Notices/0707N.pdf' },
    { sheet: '0708', name: 'COGNAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0708N.pdf' },
    { sheet: '0709', name: 'ANGOULEME', url: 'http://ficheinfoterre.brgm.fr/Notices/0709N.pdf' },
    { sheet: '0710', name: 'MONTBRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0710N.pdf' },
    { sheet: '0711', name: 'CHALUS', url: 'http://ficheinfoterre.brgm.fr/Notices/0711N.pdf' },
    { sheet: '0712', name: 'NEXON', url: 'http://ficheinfoterre.brgm.fr/Notices/0712N.pdf' },
    { sheet: '0713', name: 'CHATEAUNEUF-LA-FORET', url: 'http://ficheinfoterre.brgm.fr/Notices/0713N.pdf' },
    { sheet: '0714', name: 'BUGEAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0714N.pdf' },
    { sheet: '0715', name: 'USSEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0715N.pdf' },
    { sheet: '0730', name: 'SAINT VIVIEN DE MEDOC - SOULAC-SUR-MER', url: 'http://ficheinfoterre.brgm.fr/Notices/0730N.pdf' },
    { sheet: '0731', name: 'JONZAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0731N.pdf' },
    { sheet: '0732', name: 'BARBEZIEUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0732N.pdf' },
    { sheet: '0733', name: 'MONTMOREAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0733N.pdf' },
    { sheet: '0734', name: 'NONTRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0734N.pdf' },
    { sheet: '0735', name: 'THIVIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0735N.pdf' },
    { sheet: '0736', name: 'ST-YRIEIX-LA-PERCHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0736N.pdf' },
    { sheet: '0737', name: 'UZERCHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0737N.pdf' },
    { sheet: '0738', name: 'MEYMAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0738N.pdf' },
    { sheet: '0739', name: 'BORT-LES-ORGUES', url: 'http://ficheinfoterre.brgm.fr/Notices/0739N.pdf' },
    { sheet: '0754', name: 'LESPARRE-MEDOC - FORET DU JUNCA', url: 'http://ficheinfoterre.brgm.fr/Notices/0754N.pdf' },
    { sheet: '0755', name: 'MONTENDRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0755N.pdf' },
    { sheet: '0756', name: 'MONTGUYON', url: 'http://ficheinfoterre.brgm.fr/Notices/0756N.pdf' },
    { sheet: '0757', name: 'RIBERAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0757N.pdf' },
    { sheet: '0758', name: 'PERIGUEUX-OUEST', url: 'http://ficheinfoterre.brgm.fr/Notices/0758N.pdf' },
    { sheet: '0759', name: 'PERIGUEUX-EST', url: 'http://ficheinfoterre.brgm.fr/Notices/0759N.pdf' },
    { sheet: '0760', name: 'JUILLAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0760N.pdf' },
    { sheet: '0761', name: 'TULLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0761N.pdf' },
    { sheet: '0762', name: 'LA ROCHE-CANILLAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0762N.pdf' },
    { sheet: '0763', name: 'MAURIAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0763N.pdf' },
    { sheet: '0778', name: 'ST-LAURENT-ET-BENON', url: 'http://ficheinfoterre.brgm.fr/Notices/0778N.pdf' },
    { sheet: '0779', name: 'BLAYE', url: 'http://ficheinfoterre.brgm.fr/Notices/0779N.pdf' },
    { sheet: '0780', name: 'COUTRAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0780N.pdf' },
    { sheet: '0781', name: 'MONTPON-MENESTEROL', url: 'http://ficheinfoterre.brgm.fr/Notices/0781N.pdf' },
    { sheet: '0782', name: 'MUSSIDAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0782N.pdf' },
    { sheet: '0783', name: 'THENON', url: 'http://ficheinfoterre.brgm.fr/Notices/0783N.pdf' },
    { sheet: '0784', name: 'TERRASSON', url: 'http://ficheinfoterre.brgm.fr/Notices/0784N.pdf' },
    { sheet: '0785', name: 'BRIVE-LA-GAILLARDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0785N.pdf' },
    { sheet: '0802', name: 'STE-HELENE-LE PORGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0802N.pdf' },
    { sheet: '0803', name: 'BORDEAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0803N.pdf' },
    { sheet: '0804', name: 'LIBOURNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0804N.pdf' },
    { sheet: '0805', name: 'STE-FOY-LA-GRANDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0805N.pdf' },
    { sheet: '0806', name: 'BERGERAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0806N.pdf' },
    { sheet: '0807', name: 'LE BUGUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0807N.pdf' },
    { sheet: '0808', name: 'SARLAT-LA-CANEDA', url: 'http://ficheinfoterre.brgm.fr/Notices/0808N.pdf' },
    { sheet: '0809', name: 'SOUILLAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0809N.pdf' },
    { sheet: '0825', name: 'ARCACHON', url: 'http://ficheinfoterre.brgm.fr/Notices/0825N.pdf' },
    { sheet: '0826', name: 'AUDENGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0826N.pdf' },
    { sheet: '0827', name: 'PESSAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0827N.pdf' },
    { sheet: '0828', name: 'PODENSAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0828N.pdf' },
    { sheet: '0829', name: 'DURAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0829N.pdf' },
    { sheet: '0830', name: 'EYMET', url: 'http://ficheinfoterre.brgm.fr/Notices/0830N.pdf' },
    { sheet: '0831', name: 'BELVES', url: 'http://ficheinfoterre.brgm.fr/Notices/0831N.pdf' },
    { sheet: '0832', name: 'GOURDON', url: 'http://ficheinfoterre.brgm.fr/Notices/0832N.pdf' },
    { sheet: '0849', name: 'LA TESTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0849N.pdf' },
    { sheet: '0850', name: 'BELIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0850N.pdf' },
    { sheet: '0851', name: 'HOSTENS', url: 'http://ficheinfoterre.brgm.fr/Notices/0851N.pdf' },
    { sheet: '0852', name: 'LANGON', url: 'http://ficheinfoterre.brgm.fr/Notices/0852N.pdf' },
    { sheet: '0853', name: 'MARMANDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0853N.pdf' },
    { sheet: '0854', name: 'CANCON', url: 'http://ficheinfoterre.brgm.fr/Notices/0854N.pdf' },
    { sheet: '0855', name: 'FUMEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0855N.pdf' },
    { sheet: '0856', name: 'PUY-L\'EVEQUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0856N.pdf' },
    { sheet: '0873', name: 'BISCARROSSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0873N.pdf' },
    { sheet: '0874', name: 'PARENTIS-EN-BORN', url: 'http://ficheinfoterre.brgm.fr/Notices/0874N.pdf' },
    { sheet: '0875', name: 'ST-SYMPHORIEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0875N.pdf' },
    { sheet: '0876', name: 'BAZAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0876N.pdf' },
    { sheet: '0877', name: 'TONNEINS', url: 'http://ficheinfoterre.brgm.fr/Notices/0877N.pdf' },
    { sheet: '0878', name: 'VILLEUVE-SUR-LOT', url: 'http://ficheinfoterre.brgm.fr/Notices/0878N.pdf' },
    { sheet: '0879', name: 'PENNE-D\'AGENAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0879N.pdf' },
    { sheet: '0880', name: 'MONTCUQ', url: 'http://ficheinfoterre.brgm.fr/Notices/0880N.pdf' },
    { sheet: '0897', name: 'MIMIZAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0897N.pdf' },
    { sheet: '0898', name: 'SABRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0898N.pdf' },
    { sheet: '0899', name: 'LABRIT', url: 'http://ficheinfoterre.brgm.fr/Notices/0899N.pdf' },
    { sheet: '0900', name: 'LOSSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0900N.pdf' },
    { sheet: '0901', name: 'NERAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0901N.pdf' },
    { sheet: '0902', name: 'AGEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0902N.pdf' },
    { sheet: '0903', name: 'VALENCE-D\'AGEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0903N.pdf' },
    { sheet: '0904', name: 'MOISSAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0904N.pdf' },
    { sheet: '0923', name: 'LIT-ET-MIXE', url: 'http://ficheinfoterre.brgm.fr/Notices/0923N.pdf' },
    { sheet: '0924', name: 'MORCENX', url: 'http://ficheinfoterre.brgm.fr/Notices/0924N.pdf' },
    { sheet: '0925', name: 'BROCAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0925N.pdf' },
    { sheet: '0926', name: 'CAZAUBON', url: 'http://ficheinfoterre.brgm.fr/Notices/0926N.pdf' },
    { sheet: '0927', name: 'MONTREAL-DU-GERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0927N.pdf' },
    { sheet: '0928', name: 'CONDOM', url: 'http://ficheinfoterre.brgm.fr/Notices/0928N.pdf' },
    { sheet: '0929', name: 'ST-NICOLAS-DE-LA-GRAVE', url: 'http://ficheinfoterre.brgm.fr/Notices/0929N.pdf' },
    { sheet: '0949', name: 'SOUSTONS', url: 'http://ficheinfoterre.brgm.fr/Notices/0949N.pdf' },
    { sheet: '0950', name: 'TARTAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0950N.pdf' },
    { sheet: '0951', name: 'MONT-DE-MARSAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0951N.pdf' },
    { sheet: '0952', name: 'NOGARO', url: 'http://ficheinfoterre.brgm.fr/Notices/0952N.pdf' },
    { sheet: '0953', name: 'EAUZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0953N.pdf' },
    { sheet: '0954', name: 'FLEURANCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0954N.pdf' },
    { sheet: '0955', name: 'BEAUMONT DE LOMAGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0955N.pdf' },
    { sheet: '0976', name: 'ST-VINCENT-DE-TYROSSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0976N.pdf' },
    { sheet: '0977', name: 'DAX', url: 'http://ficheinfoterre.brgm.fr/Notices/0977N.pdf' },
    { sheet: '0978', name: 'HAGETMAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0978N.pdf' },
    { sheet: '0979', name: 'AIRE SUR L\'ADOUR', url: 'http://ficheinfoterre.brgm.fr/Notices/0979N.pdf' },
    { sheet: '0980', name: 'PLAISANCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0980N.pdf' },
    { sheet: '0981', name: 'AUCH', url: 'http://ficheinfoterre.brgm.fr/Notices/0981N.pdf' },
    { sheet: '0982', name: 'GIMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0982N.pdf' },
    { sheet: '1001', name: 'BAYONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/1001N.pdf' },
    { sheet: '1002', name: 'HASPARREN', url: 'http://ficheinfoterre.brgm.fr/Notices/1002N.pdf' },
    { sheet: '1003', name: 'ORTHEZ', url: 'http://ficheinfoterre.brgm.fr/Notices/1003N.pdf' },
    { sheet: '1004', name: 'ARTHEZ-DE-BEARN', url: 'http://ficheinfoterre.brgm.fr/Notices/1004N.pdf' },
    { sheet: '1005', name: 'LEMBEYE', url: 'http://ficheinfoterre.brgm.fr/Notices/1005N.pdf' },
    { sheet: '1006', name: 'VIC-EN-BIGORRE', url: 'http://ficheinfoterre.brgm.fr/Notices/1006N.pdf' },
    { sheet: '1007', name: 'MIRANDE', url: 'http://ficheinfoterre.brgm.fr/Notices/1007N.pdf' },
    { sheet: '1026', name: 'ESPELETTE', url: 'http://ficheinfoterre.brgm.fr/Notices/1026N.pdf' },
    { sheet: '1027', name: 'IHOLDY', url: 'http://ficheinfoterre.brgm.fr/Notices/1027N.pdf' },
    { sheet: '1028', name: 'MAULEON', url: 'http://ficheinfoterre.brgm.fr/Notices/1028N.pdf' },
    { sheet: '1068', name: 'LARRAU', url: 'http://ficheinfoterre.brgm.fr/Notices/1068N.pdf' },
    { sheet: '1069', name: 'LARUNS-SOMPORT', url: 'http://ficheinfoterre.brgm.fr/Notices/1069N.pdf' },
    { sheet: '1070', name: 'ARGELES-GAZOST', url: 'http://ficheinfoterre.brgm.fr/Notices/1070N.pdf' },
    { sheet: '1071', name: 'CAMPAN', url: 'http://ficheinfoterre.brgm.fr/Notices/1071N.pdf' },
  ],
  'occitanie': [
    { sheet: '0786', name: 'ARGENTAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0786N.pdf' },
    { sheet: '0787', name: 'PLEAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0787N.pdf' },
    { sheet: '0788', name: 'MURAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0788N.pdf' },
    { sheet: '0810', name: 'ST-CERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0810N.pdf' },
    { sheet: '0811', name: 'AURILLAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0811N.pdf' },
    { sheet: '0812', name: 'VIC-SUR-CERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0812N.pdf' },
    { sheet: '0813', name: 'CHAUDES-AIGUES', url: 'http://ficheinfoterre.brgm.fr/Notices/0813N.pdf' },
    { sheet: '0833', name: 'GRAMAT', url: 'http://ficheinfoterre.brgm.fr/Notices/0833N.pdf' },
    { sheet: '0834', name: 'LACAPELLE-MARIVAL', url: 'http://ficheinfoterre.brgm.fr/Notices/0834N.pdf' },
    { sheet: '0835', name: 'MAURS', url: 'http://ficheinfoterre.brgm.fr/Notices/0835N.pdf' },
    { sheet: '0836', name: 'ENTRAYGUES-SUR-TRUYERE', url: 'http://ficheinfoterre.brgm.fr/Notices/0836N.pdf' },
    { sheet: '0837', name: 'NASBINALS', url: 'http://ficheinfoterre.brgm.fr/Notices/0837N.pdf' },
    { sheet: '0857', name: 'ST-GERY', url: 'http://ficheinfoterre.brgm.fr/Notices/0857N.pdf' },
    { sheet: '0858', name: 'FIGEAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0858N.pdf' },
    { sheet: '0859', name: 'DECAZEVILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0859N.pdf' },
    { sheet: '0860', name: 'ESPALION', url: 'http://ficheinfoterre.brgm.fr/Notices/0860N.pdf' },
    { sheet: '0861', name: 'ST-GENIEZ-D\'OLT', url: 'http://ficheinfoterre.brgm.fr/Notices/0861N.pdf' },
    { sheet: '0881', name: 'CAHORS', url: 'http://ficheinfoterre.brgm.fr/Notices/0881N.pdf' },
    { sheet: '0882', name: 'VILLEFRANCHE DE ROUERGUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0882N.pdf' },
    { sheet: '0883', name: 'RIEUPEYROUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0883N.pdf' },
    { sheet: '0884', name: 'RODEZ', url: 'http://ficheinfoterre.brgm.fr/Notices/0884N.pdf' },
    { sheet: '0885', name: 'SEVERAC-LE-CHATEAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0885N.pdf' },
    { sheet: '0886', name: 'FLORAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0886N.pdf' },
    { sheet: '0887', name: 'GENOLHAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0887N.pdf' },
    { sheet: '0888', name: 'BESSEGES', url: 'http://ficheinfoterre.brgm.fr/Notices/0888N.pdf' },
    { sheet: '0905', name: 'CAUSSADE', url: 'http://ficheinfoterre.brgm.fr/Notices/0905N.pdf' },
    { sheet: '0906', name: 'NAJAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0906N.pdf' },
    { sheet: '0907', name: 'NAUCELLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0907N.pdf' },
    { sheet: '0908', name: 'SALLES-CURAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0908N.pdf' },
    { sheet: '0909', name: 'ST-BEAUZELY', url: 'http://ficheinfoterre.brgm.fr/Notices/0909N.pdf' },
    { sheet: '0910', name: 'MEYRUEIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0910N.pdf' },
    { sheet: '0911', name: 'ST-ANDRE-DE-VALBORGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0911N.pdf' },
    { sheet: '0912', name: 'ALES', url: 'http://ficheinfoterre.brgm.fr/Notices/0912N.pdf' },
    { sheet: '0913', name: 'PONT-ST-ESPRIT', url: 'http://ficheinfoterre.brgm.fr/Notices/0913N.pdf' },
    { sheet: '0930', name: 'MONTAUBAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0930N.pdf' },
    { sheet: '0931', name: 'NEGREPELISSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0931N.pdf' },
    { sheet: '0932', name: 'ALBI', url: 'http://ficheinfoterre.brgm.fr/Notices/0932N.pdf' },
    { sheet: '0933', name: 'CARMAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0933N.pdf' },
    { sheet: '0934', name: 'REQUISTA', url: 'http://ficheinfoterre.brgm.fr/Notices/0934N.pdf' },
    { sheet: '0935', name: 'MILLAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0935N.pdf' },
    { sheet: '0936', name: 'NANT', url: 'http://ficheinfoterre.brgm.fr/Notices/0936N.pdf' },
    { sheet: '0937', name: 'LE VIGAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0937N.pdf' },
    { sheet: '0938', name: 'ANDUZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0938N.pdf' },
    { sheet: '0939', name: 'UZES', url: 'http://ficheinfoterre.brgm.fr/Notices/0939N.pdf' },
    { sheet: '0956', name: 'GRENADE-SUR-GARONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0956N.pdf' },
    { sheet: '0957', name: 'VILLEMUR-SUR-TARN', url: 'http://ficheinfoterre.brgm.fr/Notices/0957N.pdf' },
    { sheet: '0958', name: 'GAILLAC', url: 'http://ficheinfoterre.brgm.fr/Notices/0958N.pdf' },
    { sheet: '0959', name: 'REALMONT', url: 'http://ficheinfoterre.brgm.fr/Notices/0959N.pdf' },
    { sheet: '0960', name: 'ST-SERNIN-SUR-RANCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0960N.pdf' },
    { sheet: '0961', name: 'CAMARES', url: 'http://ficheinfoterre.brgm.fr/Notices/0961N.pdf' },
    { sheet: '0962', name: 'LE CAYLAR', url: 'http://ficheinfoterre.brgm.fr/Notices/0962N.pdf' },
    { sheet: '0963', name: 'SAINT-MARTIN-SE-LONDRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0963N.pdf' },
    { sheet: '0964', name: 'SOMMIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0964N.pdf' },
    { sheet: '0965', name: 'NIMES', url: 'http://ficheinfoterre.brgm.fr/Notices/0965N.pdf' },
    { sheet: '0983', name: 'TOULOUSE-OUEST', url: 'http://ficheinfoterre.brgm.fr/Notices/0983N.pdf' },
    { sheet: '0984', name: 'TOULOUSE - EST', url: 'http://ficheinfoterre.brgm.fr/Notices/0984N.pdf' },
    { sheet: '0985', name: 'LAVAUR', url: 'http://ficheinfoterre.brgm.fr/Notices/0985N.pdf' },
    { sheet: '0986', name: 'CASTRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0986N.pdf' },
    { sheet: '0987', name: 'LACAUNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0987N.pdf' },
    { sheet: '0988', name: 'BEDARIEUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0988N.pdf' },
    { sheet: '0989', name: 'LODEVE', url: 'http://ficheinfoterre.brgm.fr/Notices/0989N.pdf' },
    { sheet: '0990', name: 'MONTPELLIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0990N.pdf' },
    { sheet: '0991', name: 'LUNEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0991N.pdf' },
    { sheet: '1008', name: 'LOMBEZ', url: 'http://ficheinfoterre.brgm.fr/Notices/1008N.pdf' },
    { sheet: '1009', name: 'MURET', url: 'http://ficheinfoterre.brgm.fr/Notices/1009N.pdf' },
    { sheet: '1010', name: 'VILLEFRANCHE DE LAURAGAIS', url: 'http://ficheinfoterre.brgm.fr/Notices/1010N.pdf' },
    { sheet: '1011', name: 'REVEL', url: 'http://ficheinfoterre.brgm.fr/Notices/1011N.pdf' },
    { sheet: '1012', name: 'MAZAMET', url: 'http://ficheinfoterre.brgm.fr/Notices/1012N.pdf' },
    { sheet: '1013', name: 'SAINT-PONS', url: 'http://ficheinfoterre.brgm.fr/Notices/1013N.pdf' },
    { sheet: '1014', name: 'ST-CHINIAN', url: 'http://ficheinfoterre.brgm.fr/Notices/1014N.pdf' },
    { sheet: '1015', name: 'PEZENAS', url: 'http://ficheinfoterre.brgm.fr/Notices/1015N.pdf' },
    { sheet: '1016', name: 'SETE', url: 'http://ficheinfoterre.brgm.fr/Notices/1016N.pdf' },
    { sheet: '1017', name: 'LE GRAU-DU-ROI', url: 'http://ficheinfoterre.brgm.fr/Notices/1017N.pdf' },
    { sheet: '1034', name: 'CAZERES', url: 'http://ficheinfoterre.brgm.fr/Notices/1034N.pdf' },
    { sheet: '1035', name: 'SAVERDUN', url: 'http://ficheinfoterre.brgm.fr/Notices/1035N.pdf' },
    { sheet: '1039', name: 'BEZIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/1039N.pdf' },
    { sheet: '1040', name: 'AGDE', url: 'http://ficheinfoterre.brgm.fr/Notices/1040N.pdf' },
    { sheet: '1061', name: 'NARBONNE', url: 'http://ficheinfoterre.brgm.fr/Notices/1061N.pdf' },
    { sheet: '1072', name: 'ARREAU', url: 'http://ficheinfoterre.brgm.fr/Notices/1072N.pdf' },
    { sheet: '1073', name: 'ASPET', url: 'http://ficheinfoterre.brgm.fr/Notices/1073N.pdf' },
    { sheet: '1074', name: 'ST-GIRONS', url: 'http://ficheinfoterre.brgm.fr/Notices/1074N.pdf' },
    { sheet: '1075', name: 'FOIX', url: 'http://ficheinfoterre.brgm.fr/Notices/1075N.pdf' },
    { sheet: '1079', name: 'LEUCATE', url: 'http://ficheinfoterre.brgm.fr/Notices/1079N.pdf' },
    { sheet: '1088', name: 'AX-LES-THERMES', url: 'http://ficheinfoterre.brgm.fr/Notices/1088N.pdf' },
    { sheet: '1089', name: 'SAINT-PAUL-DE-FENOUILLET', url: 'http://ficheinfoterre.brgm.fr/Notices/1089N.pdf' },
    { sheet: '1099', name: 'PRATS-DE-MOLLO', url: 'http://ficheinfoterre.brgm.fr/Notices/1099N.pdf' },
    { sheet: '1100', name: 'ARLES-SUR-TECH', url: 'http://ficheinfoterre.brgm.fr/Notices/1100N.pdf' },
  ],
  'pays-de-la-loire': [
    { sheet: '0248', name: 'LANDIVY', url: 'http://ficheinfoterre.brgm.fr/Notices/0248N.pdf' },
    { sheet: '0284', name: 'ERNEE', url: 'http://ficheinfoterre.brgm.fr/Notices/0284N.pdf' },
    { sheet: '0285', name: 'MAYENNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0285N.pdf' },
    { sheet: '0286', name: 'VILLAINES-LA-JUHEL', url: 'http://ficheinfoterre.brgm.fr/Notices/0286N.pdf' },
    { sheet: '0287', name: 'FRESNAY SUR SARTHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0287N.pdf' },
    { sheet: '0288', name: 'MAMERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0288N.pdf' },
    { sheet: '0317', name: 'RENNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0317N.pdf' },
    { sheet: '0318', name: 'VITRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0318N.pdf' },
    { sheet: '0319', name: 'LAVAL', url: 'http://ficheinfoterre.brgm.fr/Notices/0319N.pdf' },
    { sheet: '0320', name: 'EVRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0320N.pdf' },
    { sheet: '0321', name: 'SILLE-LE-GUILLAUME', url: 'http://ficheinfoterre.brgm.fr/Notices/0321N.pdf' },
    { sheet: '0322', name: 'BEAUMONT-SUR-SARTHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0322N.pdf' },
    { sheet: '0353', name: 'JANZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0353N.pdf' },
    { sheet: '0354', name: 'LA GUERCHE-DE-BRETAGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0354N.pdf' },
    { sheet: '0355', name: 'COSSE-LE-VIVIEN', url: 'http://ficheinfoterre.brgm.fr/Notices/0355N.pdf' },
    { sheet: '0356', name: 'MESLAY-DU-MAINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0356N.pdf' },
    { sheet: '0357', name: 'LOUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0357N.pdf' },
    { sheet: '0358', name: 'LE MANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0358N.pdf' },
    { sheet: '0388', name: 'BAIN-DE-BRETAGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0388N.pdf' },
    { sheet: '0389', name: 'CHATEAUBRIANT', url: 'http://ficheinfoterre.brgm.fr/Notices/0389N.pdf' },
    { sheet: '0390', name: 'CRAON', url: 'http://ficheinfoterre.brgm.fr/Notices/0390N.pdf' },
    { sheet: '0391', name: 'CHATEAU-GONTIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0391N.pdf' },
    { sheet: '0392', name: 'LA FLECHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0392N.pdf' },
    { sheet: '0393', name: 'ECOMMOY', url: 'http://ficheinfoterre.brgm.fr/Notices/0393N.pdf' },
    { sheet: '0419', name: 'REDON', url: 'http://ficheinfoterre.brgm.fr/Notices/0419N.pdf' },
    { sheet: '0420', name: 'NOZAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0420N.pdf' },
    { sheet: '0421', name: 'ST-MARS-LA-JAILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0421N.pdf' },
    { sheet: '0422', name: 'SEGRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0422N.pdf' },
    { sheet: '0423', name: 'LE LION D\'ANGERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0423N.pdf' },
    { sheet: '0424', name: 'BAUGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0424N.pdf' },
    { sheet: '0425', name: 'LE LUDE', url: 'http://ficheinfoterre.brgm.fr/Notices/0425N.pdf' },
    { sheet: '0450', name: 'SAVENAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0450N.pdf' },
    { sheet: '0451', name: 'NORT-SUR-ERDRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0451N.pdf' },
    { sheet: '0452', name: 'ANCENIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0452N.pdf' },
    { sheet: '0453', name: 'CHALONNES-SUR-LOIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0453N.pdf' },
    { sheet: '0454', name: 'ANGERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0454N.pdf' },
    { sheet: '0455', name: 'LONGUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0455N.pdf' },
    { sheet: '0456', name: 'NOYANT', url: 'http://ficheinfoterre.brgm.fr/Notices/0456N.pdf' },
    { sheet: '0480', name: 'PAIMBOEUF', url: 'http://ficheinfoterre.brgm.fr/Notices/0480N.pdf' },
    { sheet: '0481', name: 'NANTES', url: 'http://ficheinfoterre.brgm.fr/Notices/0481N.pdf' },
    { sheet: '0482', name: 'VALLET', url: 'http://ficheinfoterre.brgm.fr/Notices/0482N.pdf' },
    { sheet: '0483', name: 'CHEMILLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0483N.pdf' },
    { sheet: '0484', name: 'THOUARCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0484N.pdf' },
    { sheet: '0485', name: 'SAUMUR', url: 'http://ficheinfoterre.brgm.fr/Notices/0485N.pdf' },
    { sheet: '0486', name: 'CHINON', url: 'http://ficheinfoterre.brgm.fr/Notices/0486N.pdf' },
    { sheet: '0506', name: 'ILE-DE-NOIRMOUTIER POINTE-DE-ST-GILDAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0506N.pdf' },
    { sheet: '0507', name: 'MACHECOUL', url: 'http://ficheinfoterre.brgm.fr/Notices/0507N.pdf' },
    { sheet: '0508', name: 'ST-PHILBERT-DE-GRAND-LIEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0508N.pdf' },
    { sheet: '0509', name: 'CLISSON', url: 'http://ficheinfoterre.brgm.fr/Notices/0509N.pdf' },
    { sheet: '0510', name: 'CHOLET', url: 'http://ficheinfoterre.brgm.fr/Notices/0510N.pdf' },
    { sheet: '0511', name: 'VIHIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0511N.pdf' },
    { sheet: '0512', name: 'MONTREUIL-BELLAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0512N.pdf' },
    { sheet: '0513', name: 'LOUDUN', url: 'http://ficheinfoterre.brgm.fr/Notices/0513N.pdf' },
    { sheet: '0534', name: 'CHALLANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0534N.pdf' },
    { sheet: '0535', name: 'PALLUAU', url: 'http://ficheinfoterre.brgm.fr/Notices/0535N.pdf' },
    { sheet: '0536', name: 'MONTAIGU', url: 'http://ficheinfoterre.brgm.fr/Notices/0536N.pdf' },
    { sheet: '0537', name: 'LES HERBIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0537N.pdf' },
    { sheet: '0538', name: 'BRESSUIRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0538N.pdf' },
    { sheet: '0539', name: 'THOUARS', url: 'http://ficheinfoterre.brgm.fr/Notices/0539N.pdf' },
    { sheet: '0540', name: 'LENCLOITRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0540N.pdf' },
    { sheet: '0559', name: 'ILED\'YEU', url: 'http://ficheinfoterre.brgm.fr/Notices/0559N.pdf' },
    { sheet: '0560', name: 'ST-GILLES-CROIX-DE-VIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0560N.pdf' },
    { sheet: '0561', name: 'LE POIRE-SUR-VIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0561N.pdf' },
    { sheet: '0562', name: 'LA ROCHE SUR YON', url: 'http://ficheinfoterre.brgm.fr/Notices/0562N.pdf' },
    { sheet: '0563', name: 'CHANTONNAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0563N.pdf' },
    { sheet: '0564', name: 'MONCOUTANT', url: 'http://ficheinfoterre.brgm.fr/Notices/0564N.pdf' },
    { sheet: '0565', name: 'PARTHENAY', url: 'http://ficheinfoterre.brgm.fr/Notices/0565N.pdf' },
    { sheet: '0566', name: 'MIREBEAU-EN-POITOU', url: 'http://ficheinfoterre.brgm.fr/Notices/0566N.pdf' },
    { sheet: '0585', name: 'LUCON', url: 'http://ficheinfoterre.brgm.fr/Notices/0585N.pdf' },
    { sheet: '0586', name: 'FONTENAY-LE-COMTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0586N.pdf' },
    { sheet: '0587', name: 'COULONGE-SUR-L\'AUTIZE', url: 'http://ficheinfoterre.brgm.fr/Notices/0587N.pdf' },
    { sheet: '0588', name: 'MAZIERES-EN-GATINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0588N.pdf' },
    { sheet: '0589', name: 'POITIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0589N.pdf' },
    { sheet: '0608', name: 'L\'AIGUILLON-SUR-MER', url: 'http://ficheinfoterre.brgm.fr/Notices/0608N.pdf' },
    { sheet: '0609', name: 'MARANS', url: 'http://ficheinfoterre.brgm.fr/Notices/0609N.pdf' },
    { sheet: '0610', name: 'NIORT', url: 'http://ficheinfoterre.brgm.fr/Notices/0610N.pdf' },
    { sheet: '0611', name: 'ST-MAIXENT L\'ECOLE', url: 'http://ficheinfoterre.brgm.fr/Notices/0611N.pdf' },
    { sheet: '0612', name: 'LUSIGNAN', url: 'http://ficheinfoterre.brgm.fr/Notices/0612N.pdf' },
  ],
  'provence-alpes-cote-dazur': [
    { sheet: '0798', name: 'LA GRAVE', url: 'http://ficheinfoterre.brgm.fr/Notices/0798N.pdf' },
    { sheet: '0823', name: 'BRIANCON', url: 'http://ficheinfoterre.brgm.fr/Notices/0823N.pdf' },
    { sheet: '0845', name: 'ST-BONNET', url: 'http://ficheinfoterre.brgm.fr/Notices/0845N.pdf' },
    { sheet: '0846', name: 'ORCIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0846N.pdf' },
    { sheet: '0847', name: 'GUILLESTRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0847N.pdf' },
    { sheet: '0848', name: 'AIGUILLES  COL SAINT-MARTIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0848N.pdf' },
    { sheet: '0869', name: 'GAP', url: 'http://ficheinfoterre.brgm.fr/Notices/0869N.pdf' },
    { sheet: '0870', name: 'CHORGES', url: 'http://ficheinfoterre.brgm.fr/Notices/0870N.pdf' },
    { sheet: '0871', name: 'EMBRUN-GUILLESTRE', url: 'http://ficheinfoterre.brgm.fr/Notices/0871N.pdf' },
    { sheet: '0872', name: 'AIGUILLE DE CHAMBEYRON', url: 'http://ficheinfoterre.brgm.fr/Notices/0872N.pdf' },
    { sheet: '0890', name: 'VALREAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0890N.pdf' },
    { sheet: '0892', name: 'SERRES', url: 'http://ficheinfoterre.brgm.fr/Notices/0892N.pdf' },
    { sheet: '0893', name: 'LARAGNE-MONTEGLIN', url: 'http://ficheinfoterre.brgm.fr/Notices/0893N.pdf' },
    { sheet: '0894', name: 'SEYNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0894N.pdf' },
    { sheet: '0895', name: 'BARCELONNETTE', url: 'http://ficheinfoterre.brgm.fr/Notices/0895N.pdf' },
    { sheet: '0896', name: 'LARCHE', url: 'http://ficheinfoterre.brgm.fr/Notices/0896N.pdf' },
    { sheet: '0914', name: 'ORANGE', url: 'http://ficheinfoterre.brgm.fr/Notices/0914N.pdf' },
    { sheet: '0915', name: 'VAISON-LA-ROMAINE', url: 'http://ficheinfoterre.brgm.fr/Notices/0915N.pdf' },
    { sheet: '0916', name: 'SEDERON', url: 'http://ficheinfoterre.brgm.fr/Notices/0916N.pdf' },
    { sheet: '0917', name: 'SISTERON', url: 'http://ficheinfoterre.brgm.fr/Notices/0917N.pdf' },
    { sheet: '0918', name: 'LA JAVIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0918N.pdf' },
    { sheet: '0919', name: 'ALLOS', url: 'http://ficheinfoterre.brgm.fr/Notices/0919N.pdf' },
    { sheet: '0920', name: 'ST-ETIENNE-DE-TINEE', url: 'http://ficheinfoterre.brgm.fr/Notices/0920N.pdf' },
    { sheet: '0940', name: 'AVIGNON', url: 'http://ficheinfoterre.brgm.fr/Notices/0940N.pdf' },
    { sheet: '0941', name: 'CARPENTRAS', url: 'http://ficheinfoterre.brgm.fr/Notices/0941N.pdf' },
    { sheet: '0942', name: 'SAULT-DE-VAUCLUSE', url: 'http://ficheinfoterre.brgm.fr/Notices/0942N.pdf' },
    { sheet: '0943', name: 'FORCALQUIER', url: 'http://ficheinfoterre.brgm.fr/Notices/0943N.pdf' },
    { sheet: '0944', name: 'DIGNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0944N.pdf' },
    { sheet: '0945', name: 'ENTREVAUX', url: 'http://ficheinfoterre.brgm.fr/Notices/0945N.pdf' },
    { sheet: '0946', name: 'PUGET-THENIERS', url: 'http://ficheinfoterre.brgm.fr/Notices/0946N.pdf' },
    { sheet: '0947', name: 'ST-MARTIN-VESUBIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0947N.pdf' },
    { sheet: '0966', name: 'CHATEAURENARD', url: 'http://ficheinfoterre.brgm.fr/Notices/0966N.pdf' },
    { sheet: '0967', name: 'CAVAILLON', url: 'http://ficheinfoterre.brgm.fr/Notices/0967N.pdf' },
    { sheet: '0968', name: 'REILLANNE', url: 'http://ficheinfoterre.brgm.fr/Notices/0968N.pdf' },
    { sheet: '0969', name: 'MANOSQUE', url: 'http://ficheinfoterre.brgm.fr/Notices/0969N.pdf' },
    { sheet: '0970', name: 'MOUSTIERS-STE-MARIE', url: 'http://ficheinfoterre.brgm.fr/Notices/0970N.pdf' },
    { sheet: '0971', name: 'CASTELLANE', url: 'http://ficheinfoterre.brgm.fr/Notices/0971N.pdf' },
    { sheet: '0972', name: 'ROQUESTERON', url: 'http://ficheinfoterre.brgm.fr/Notices/0972N.pdf' },
    { sheet: '0973', name: 'MENTON-NICE', url: 'http://ficheinfoterre.brgm.fr/Notices/0973N.pdf' },
    { sheet: '0992', name: 'ARLES', url: 'http://ficheinfoterre.brgm.fr/Notices/0992N.pdf' },
    { sheet: '0993', name: 'EYGUIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/0993N.pdf' },
    { sheet: '0994', name: 'SALON-DE-PROVENCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0994N.pdf' },
    { sheet: '0995', name: 'PERTUIS', url: 'http://ficheinfoterre.brgm.fr/Notices/0995N.pdf' },
    { sheet: '0996', name: 'TAVERNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0996N.pdf' },
    { sheet: '0997', name: 'SALERNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0997N.pdf' },
    { sheet: '0998', name: 'FAYENCE', url: 'http://ficheinfoterre.brgm.fr/Notices/0998N.pdf' },
    { sheet: '0999', name: 'GRASSE-CANNES', url: 'http://ficheinfoterre.brgm.fr/Notices/0999N.pdf' },
    { sheet: '1018', name: 'SAINTES-MARIES-DE-LA-MER', url: 'http://ficheinfoterre.brgm.fr/Notices/1018N.pdf' },
    { sheet: '1019', name: 'ISTRES', url: 'http://ficheinfoterre.brgm.fr/Notices/1019N.pdf' },
    { sheet: '1021', name: 'AIX-EN-PROVENCE', url: 'http://ficheinfoterre.brgm.fr/Notices/1021N.pdf' },
    { sheet: '1022', name: 'BRIGNOLES', url: 'http://ficheinfoterre.brgm.fr/Notices/1022N.pdf' },
    { sheet: '1023', name: 'DRAGUIGNAN', url: 'http://ficheinfoterre.brgm.fr/Notices/1023N.pdf' },
    { sheet: '1045', name: 'CUERS', url: 'http://ficheinfoterre.brgm.fr/Notices/1045N.pdf' },
    { sheet: '1046', name: 'COLLOBRIERES', url: 'http://ficheinfoterre.brgm.fr/Notices/1046N.pdf' },
    { sheet: '1047', name: 'ST-TROPEZ', url: 'http://ficheinfoterre.brgm.fr/Notices/1047N.pdf' },
  ],
}
